/* Data definitions for military units in the conquer world */
/* conquer : Copyright (c) 1992 by Ed Barlow and Adam Bryant
 *
 * A good deal of time and effort has gone into the writing of this
 * code and it is our hope that you respect this.  We give permission
 * to alter the code, but not to redistribute modified versions of the
 * code without our explicit permission.  If you do modify the code,
 * please document the changes made, and send us a copy, so that all
 * people may have it.  The code, to the best of our knowledge, works
 * well, but there will probably always be a need for bug fixes and
 * improvements.  We disclaim any responsibility for the codes'
 * actions.  [Use at your own risk].  This notice is just our way of
 * saying, "Happy gaming!", while making an effort to not get sued in
 * the process.
 *                           Ed Barlow, Adam Bryant
 */
#define DATA_DECLARE
#include "dataX.h"
#undef DATA_DECLARE
#include "armyX.h"
#include "navyX.h"
#include "magicX.h"
#include "statusX.h"

/* Army Unit Descriptions */
/* If adding or deleting any types, change DEFAULT_ settings in armyX.h */
AINFO_STRUCT ainfo_list[] = {

  /* The list of leader types */
  {"King", "King", "King",
     "A noble ruler, whose population follows his hereditary decisions",
     UP_RULER | UP_FREESUPPLY,
     AC_LEADER,
     100, 30, 30, 20, 0L, 0L, 50L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Baron", "Baron", "Baron",
     "This noble leader supports the King in all endeavors",
     UP_FREESUPPLY,
     AC_LEADER,
     50, 20, 20, 20, 0L, 0L, 50L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Emperor", "Empr", "Emperor",
     "Ruling over a vast realm is the dream of every Emperor",
     UP_RULER | UP_FREESUPPLY,
     AC_LEADER,
     100, 30, 30, 20, 0L, 0L, 50L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Prince", "Prnc", "Prince",
     "Striving to please ones emperor is of highest importance",
     UP_FREESUPPLY,
     AC_LEADER,
     50, 20, 20, 20, 0L, 0L, 50L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Wizard", "Wzrd", "Wizard",
     "Magic powerful enough to rule a realm",
     UP_RULER | UP_FREESUPPLY | UP_SPELLCAST | UP_FULLCASTER,
     AC_LEADER,
     250, 30, 30, 20, 0L, 0L, 25L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Mage", "Mage", "Mage",
     "Dutiously studying the arcane arts in support of Wizardly Master",
     UP_FREESUPPLY | UP_SPELLCAST,
     AC_LEADER,
     50, 20, 20, 20, 0L, 0L, 25L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Pope", "Pope", "Pope",
     "A great religious leader, the spiritual essense of his nation",
     UP_RULER | UP_FREESUPPLY,
     AC_LEADER,
     100, 30, 30, 20, 0L, 0L, 50L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Cardinal", "Cdnl", "Cardinal",
     "Dedication to the Pope is of the highest honor and duty",
     UP_FREESUPPLY,
     AC_LEADER,
     50, 20, 20, 20, 0L, 0L, 50L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Admiral", "Adml", "Admiral",
     "Knowledge of the seas formed the source of power of this nation ruler",
     UP_RULER | UP_FREESUPPLY,
     AC_LEADER,
     100, 30, 30, 20, 0L, 0L, 33L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Captain", "Capt", "Captain",
     "Sailing the seas to expand the reach of the Admiral",
     UP_FREESUPPLY,
     AC_LEADER,
     50, 20, 20, 20, 0L, 0L, 33L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Warlord", "Wrld", "Warlord",
     "Among the elite of warriors, fighting prowess veteran builds a nation",
     UP_RULER | UP_FREESUPPLY,
     AC_LEADER,
     250, 35, 35, 20, 0L, 0L, 25L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Lord", "Lord", "Lord",
     "Skilled in armed combat, this soldier knows how to serve the Warlord",
     UP_FREESUPPLY,
     AC_LEADER,
     125, 30, 30, 20, 0L, 0L, 25L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Demon", "Demn", "Demon",
     "Spoken of in hushed tones among the populous, a fearsome ruler indeed",
     UP_RULER | UP_FREESUPPLY,
     AC_LEADER,
     250, 50, 50, 20, 0L, 0L, 10L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Devil", "Devl", "Devil",
     "Worshipful of the Demon above all others in the realm",
     UP_FREESUPPLY,
     AC_LEADER,
     75, 20, 20, 20, 0L, 0L, 10L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Dragyn", "Dgyn", "Dragyn",
     "Powerful and awe-inspiring, this monster wields might wherever possible",
     UP_RULER | UP_FREESUPPLY,
     AC_LEADER,
     500, 50, 50, 20, 0L, 0L, 10L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Wyrm", "Wyrm", "Wyrm",
     "Ever striving to serve the powerful Dragyn",
     UP_FREESUPPLY,
     AC_LEADER,
     100, 40, 40, 20, 0L, 0L, 10L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Shadow", "Shdw", "Shadow",
     "Cold, dark and deadly, this ruler is ever searching for more power",
     UP_RULER | UP_FREESUPPLY | UP_UNDEAD,
     AC_LEADER,
     250, 50, 50, 20, 0L, 0L, 5L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Nazgul", "Nzgl", "Nazgul",
     "Deadly in their own right, Shadow's servants bring power to their lord",
     UP_FREESUPPLY | UP_UNDEAD,
     AC_LEADER,
     125, 40, 40, 20, 0L, 0L, 5L, 1, 1,
     0x0L, 0x0L, 0x0L },

  /* The special spell casters */
  {"Sorcerer", "Sorc", "Sorcerer",
     "An extremely skilled spell caster, a master of the arts",
     UP_FREESUPPLY | UP_FULLCASTER | UP_SPELLCAST,
     AC_SPELLCASTER,
     100, 10, 10, 10, 0L, 0L, 0L, 1, 1,
     0x0L, 0x0L, 0x0L },
  {"Magician", "Magn", "Magician",
     "A spellcaster who loyally provides magical skills for a nation",
     UP_FREESUPPLY | UP_SPELLCAST,
     AC_SPELLCASTER,
     50, 0, 0, 10, 0L, 0L, 0L, 1, 1,
     0x0L, 0x0L, 0x0L },

  /* The list of monster types */
  {"Spirit", "spir", "spirit",
     "Not among the strongest of monsters, the spirit is conjurable by many",
     UP_FLIGHT,
     AC_MONSTER,
     50, 0, 0, 10, 1800L, 1L, 1000L, 150, 100,
     0x0L, 0x0L, 0x0L },
  {"Assassin", "Assn", "Assassin",
     "Deadly and swift, this monster is feared by much of mankind",
     UP_SIGHT | UP_SLIPPERY,
     AC_MONSTER,
     50, 20, 20, 10, 1400L, 2L, 1000L, 250, 50,
     MM_NINJA, 0x0L, 0x0L },
  {"Efreet", "efr", "efreet",
     "Conjured from and composed of Air, this spirit is a helpful ally",
     UP_FLIGHT,
     AC_MONSTER,
     50, 10, 10, 15, 1200L, 2L, 800L, 200, 100,
     0x0L, 0x0L, MW_AIR },
  {"Gargoyle", "garg", "gargoyle",
     "Skulking and devious, the fiendish gargoyle can be a powerful enemy",
     UP_FLIGHT,
     AC_MONSTER,
     75, 10, 10, 10, 2000L, 2L, 1150L, 170, 120,
     MM_ORC, 0x0L, 0x0L },
  {"Wraith", "Wra", "Wraith",
     "This fearsome spectre is a bane of all that is good",
     UP_UNDEAD,
     AC_MONSTER,
     75, 10, 10, 10, 2000L, 3L, 1300L, 250, 100,
     0x0L, 0x0L, MW_VAMPIRE | MW_THEVOID },
  {"Hero", "Hero", "Hero",
     "A powerful warrior who comes to serve the worthy",
     0x0L,
     AC_MONSTER,
     100, 0, 0, 10, 1600L, 3L, 800L, 300, 200,
     MM_WARRIOR, 0x0L, 0x0L },
  {"Centaur", "Cent", "Centaur",
     "Half human, half horse, this creature proves a valient fighter",
     UP_ANTIAIR,
     AC_MONSTER,
     75, 10, 10, 15, 1700L, 3L, 800L, 250, 150,
     MM_EQUINE, 0x0L, 0x0L },
  {"Lich", "Lich", "@Lich",
     "An undead wizard whose life force is sustained by its own magic",
     UP_SPELLCAST | UP_FULLCASTER | UP_UNDEAD | UP_NODRAFT,
     AC_MONSTER,
     100, 0, 0, 10, 0L, 0L, 1200L, 300, 100,
     0x0L, 0x0L, MW_VAMPIRE },
  {"Giant", "Gnt", "Giant",
     "Large in stature and powerful in strength; a formidable opponent",
     UP_FORTDAMAGE,
     AC_MONSTER,
     150, 0, 0, 10, 2500L, 5L, 2100L, 500, 300,
     0x0L, 0x0L, 0x0L },
  {"SuperHero", "SHro", "SuperHero",
     "Superb fighting skills cause consternation among enemies",
     0x0L,
     AC_MONSTER,
     150, 15, 15, 10, 2600L, 5L, 1200L, 500, 300,
     MM_WARRIOR | MM_CAPTAIN, 0x0L, 0x0L },
  {"Mummy", "Mumm", "Mummy",
     "Though in the midst of a full body wrap, fighting skills go unhindered",
     UP_UNDEAD,
     AC_MONSTER,
     150, 15, 15, 10, 2300L, 5L, 1600L, 400, 150,
     0x0L, 0x0L, MW_VAMPIRE },
  {"Earthmental", "Elem", "Earth Elem",
     "Formed from dirt and rocks, this creature's might is well respected",
     UP_EARTHTYPE | UP_FORTDAMAGE,
     AC_MONSTER,
     175, 5, 5, 15, 2500L, 6L, 2000L, 600, 200,
     0x0L, 0x0L, MW_EARTH },
  {"Minotaur", "mino", "minotaur",
     "Half Bull, Half Human; no one dares to say this creature is full of it",
     0x0L,
     AC_MONSTER,
     150, 20, 20, 10, 2500L, 8L, 1800L, 500, 250,
     0x0L, 0x0L, MW_WYZARD },
  {"Daemon", "daem", "daemon",
     "Full of might and power, a force to be feared",
     0x0L,
     AC_MONSTER,
     500, 50, 50, 10, 10000L, 10L, 6000L, 1300, 400,
     MM_ORC, 0x0L, MW_WYZARD | MW_SORCERER },
  {"Balrog", "Bal", "Balrog",
     "Demonic and full of Fire, a Bane of all life",
     UP_FIRETYPE | UP_FLIGHT,
     AC_MONSTER,
     500, 40, 40, 15, 12000L, 12L, 6000L, 1500, 400,
     MM_ORC | MM_OGRE, 0x0L, MW_WYZARD | MW_SORCERER | MW_FIRE },
  {"Dragon", "Drgn", "Dragon",
     "Perhaps the greatest of all beasts, this creature is most feared",
     UP_FIRETYPE | UP_FLIGHT | UP_FORTDAMAGE | UP_SPELLCAST,
     AC_MONSTER,
     1000, 50, 50, 20, 20000L, 15L, 10000L, 3000, 500,
     MM_DRAGON | MM_OGRE | MM_ORC, 0x0L, MW_WYZARD | MW_SORCERER },

  /* The normal army units */
  {"Militia", "mlta", "mlta",
     "Not very well trained or supplied, but when it is all you've got...",
     UP_HALFRECRUIT,
     AC_NORMAL,
     1, -40, -25, 0, 0L, 50L, 20L, 5, 8,
     0x0L, 0x0L, 0x0L },
  {"Goblins", "gob", "gbln",
     "Ever eager to die in the name of their horribly monstrous leader",
     0x0L,
     AC_ORCISH,
     1, -15, -15, 10, 80L, 70L, 20L, 8, 7,
     MM_ORC, 0x0L, 0x0L },
  {"Orcs", "orc", "orc",
     "Fearsome in mere numbers, these units provide capable soldiers",
     0x0L,
     AC_ORCISH,
     1, 0, 0, 10, 80L, 85L, 50L, 10, 8,
     MM_ORC, 0x0L, 0x0L },
  {"Infantry", "inf", "infy",
     "The basic military unit, given normal training and supplies",
     0x0L,
     AC_NORMAL,
     1, 0, 0, 10, 100L, 100L, 50L, 10, 10,
     0x0L, 0x0L, 0x0L },
  {"Sailors", "Sail", "Sail",
     "Normal sea transported troops, these units may only take unowned land",
     UP_UNLOAD,
     AC_SAILORS,
     1, 0, 0, 0, 100L, 100L, 50L, 10, 10,
     0x0L, 0x0L, 0x0L },
  {"Marines", "Marn", "XMrn",
     "Skilled naval based units, these units take and hold beach heads",
     UP_UNLOAD | UP_NAVALTAKE,
     AC_SAILORS,
     1, 5, 0, 0, 100L, 100L, 50L, 11, 11,
     0x0L, MC_SAILOR, 0x0L },
  {"Assault", "Aslt", "Aslt",
     "These elite naval based units are used to expand beach heads outward",
     UP_UNLOAD | UP_NAVALTAKE,
     AC_SAILORS,
     1, 10, 5, 5, 120L, 125L, 60L, 12, 11,
     0x0L, MC_MARINE, 0x0L },
  {"Archers", "arch", "arch",
     "Trained in the use of archery, these units provide excellent defense",
     UP_ANTIAIR | UP_BALLISTICS,
     AC_ARCHERS,
     1, 0, 10, 10, 100L, 100L, 50L, 11, 10,
     MM_ARCHERY, 0x0L, 0x0L },
  {"Uruk-Hai", "Uruk", "Uruk",
     "These skilled troops are better trained and supplied than normal Orcs",
     0x0L,
     AC_ORCISH,
     1, 5, 5, 10, 150L, 125L, 50L, 11, 10,
     MM_OGRE | MM_ORC, 0x0L, 0x0L },
  {"Ninjas", "Nnja", "Nnja",
     "Trained in scouting and combat, these units make excellent vanguards",
     UP_SIGHT | UP_SLIPPERY | UP_SPCLTRAIN,
     AC_NORMAL,
     1, 20, 0, 10, 150L, 125L, 50L, 10, 10,
     MM_NINJA, 0x0L, 0x0L },
  {"Longbowmen", "Bmen", "bmen",
     "Archers armed with longbows provide an even more devastating barrage",
     UP_ANTIAIR | UP_BALLISTICS,
     AC_ARCHERS,
     1, 5, 15, 10, 150L, 150L, 65L, 11, 10,
     MM_ARCHERY | MM_WARRIOR, 0x0L, 0x0L },
  {"Phalanx", "Phax", "Plnx",
     "Trained to fight as a whole, such troops make good central units",
     UP_NEEDMIN,
     AC_NORMAL,
     500, 10, 10, 10, 150L, 150L, 60L, 11, 10,
     MM_WARRIOR | MM_CAPTAIN, 0x0L, 0x0L },
  {"Bow_Phalanx", "Blnx", "BPlnx",
     "A well trained legion of bowmen these archers work best in unison", 
     UP_ANTIAIR | UP_BALLISTICS | UP_NEEDMIN,
     AC_ARCHERS,
     500, 20, 20, 10, 160L, 170L, 80L, 11, 10,
     MM_ARCHERY | MM_WARRIOR | MM_CAPTAIN, 0x0L, 0x0L },
  {"Olog-Hai", "Olog", "Olog",
     "These elite Orcish units form excellent fighting troops",
     0x0L,
     AC_ORCISH,
     1, 15, 15, 10, 150L, 180L, 75L, 11, 11,
     MM_DRAGON | MM_OGRE | MM_ORC, MC_BREEDER, 0x0L },
  {"Legionaries", "Legn", "Lgn",
     "These elite infantry troops are trained to fight as one",
     UP_NEEDMIN,
     AC_NORMAL,
     1000, 20, 20, 10, 150L, 180L, 80L, 11, 11,
     MM_WARRIOR | MM_CAPTAIN | MM_WARLORD, 0x0L, 0x0L },
  {"Dragoons", "Dgon", "Dgoon",
     "Mobile and well supplied, these troops perform fast powerful strikes",
     0x0L,
     AC_CAVALRY,
     1, 10, 10, 15, 100L, 200L, 150L, 11, 10,
     0x0L, 0x0L, 0x0L },
  {"Full_Bowmen", "Fbow", "Fbow",
     "A well trained legion of bowmen these archers work best in unison", 
     UP_ANTIAIR | UP_BALLISTICS | UP_NEEDMIN,
     AC_ARCHERS,
     1000, 30, 30, 10, 160L, 200L, 110L, 12, 10,
     MM_ARCHERY | MM_WARRIOR | MM_WARLORD | MM_CAPTAIN, 0x0L, 0x0L },
  {"Crossbows", "Cbow", "Cbow",
     "Crossbow archers provide a powerful offense, but are easy to attack",
     UP_ANTIAIR | UP_BALLISTICS,
     AC_ARCHERS,
     1, 40, 0, 10, 200L, 200L, 130L, 12, 10,
     MM_ARCHERY | MM_WARRIOR | MM_WARLORD | MM_CAPTAIN, 0x0L, 0x0L },
  {"Mercenaries", "Merc", "Merc",
     "Soldiers for hire, they need only be paid to do their work",
     UP_PAYOFF | UP_ANYDISB,
     AC_MERCS,
     1, 0, 0, 10, 0L, 225L, 100L, 10, 9,
     0x0L, 0x0L, 0x0L },
  {"Merc_Arch", "MArc", "archers",
     "Archers for hire, they need only be paid to do their work",
     UP_PAYOFF | UP_ANYDISB | UP_ANTIAIR | UP_BALLISTICS,
     AC_MERCS,
     1, 0, 10, 10, 0L, 250L, 110L, 10, 9,
     0x0L, 0x0L, 0x0L },
  {"Merc_Asslt", "MAst", "Assault",
     "Pirates for hire, they need only be paid to do their work",
     UP_PAYOFF | UP_ANYDISB | UP_UNLOAD | UP_NAVALTAKE,
     AC_MERCS,
     1, 10, 5, 5, 0L, 275L, 120L, 10, 9,
     0x0L, 0x0L, 0x0L },
  {"Merc_Drag", "Mdgn", "Dragoons",
     "Dragoon fighters who are available at a price",
     UP_PAYOFF | UP_ANYDISB,
     AC_MERCS,
     1, 10, 10, 15, 0L, 300L, 160L, 11, 9,
     0x0L, 0x0L, 0x0L },
  {"Merc_Lt_Cav", "Mlcv", "Lt Cavalry",
     "Lighly armored cavalry, they are available at the right price",
     UP_PAYOFF | UP_ANYDISB,
     AC_MERCS,
     1, 20, 20, 20, 0L, 350L, 200L, 11, 9,
     0x0L, 0x0L, 0x0L },
  {"Merc_Hv_Cav", "Mhcv", "Hvy Cavalry",
     "Armored cavalry, they are available for the right price",
     UP_PAYOFF | UP_ANYDISB,
     AC_MERCS,
     1, 30, 30, 18, 0L, 500L, 275L, 12, 9,
     0x0L, 0x0L, 0x0L },
  {"Merc_Rocs", "MRoc", "Rocs",
     "Flying mercenary troops are the top of the line paid troops",
     UP_PAYOFF | UP_ANYDISB | UP_FLIGHT | UP_ARROWWEAK,
     AC_MERCS,
     1, 20, 30, 10, 0L, 750L, 400L, 12, 9,
     0x0L, 0x0L, 0x0L },
  {"Trolls", "Trol", "Trll",
     "Strong magical beasts enlisted to serve within the Orcish military",
     0x0L,
     AC_UNIQUE,
     1, 25, 15, 10, 200L, 225L, 100L, 13, 12,
     MM_DRAGON | MM_OGRE | MM_ORC, 0x0L, MW_WYZARD },
  {"Inf. Elite", "IElt", "IElt",
     "Well trained and supplied, these troops provide swifter foot soldiers",
     0x0L,
     AC_NORMAL,
     1, 20, 20, 13, 200L, 225L, 100L, 13, 11,
     MM_ARMOR, 0x0L, 0x0L },
  {"Hvy_Bowmen", "Hbow", "Hbow",
     "Toughly armored, and heavily supplied, these bowmen are formidable",
     UP_ANTIAIR | UP_BALLISTICS | UP_NEEDMIN,
     AC_ARCHERS,
     2000, 40, 30, 10, 225L, 240L, 120L, 13, 10,
     MM_ARCHERY | MM_ARMOR | MM_WARRIOR | MM_WARLORD | MM_CAPTAIN, 0x0L, 0x0L},
  {"Lt_Cavalry", "lCav", "lCav",
     "Lightly armored cavalry troops operate as a very fast military force",
     0x0L,
     AC_CAVALRY,
     1, 20, 20, 20, 100L, 300L, 175L, 13, 10,
     MM_EQUINE | MM_WARRIOR, 0x0L, 0x0L },
  {"Hv_Cavalry", "hCav", "hCav",
     "Sacrificing some speed for protection, these horsemen are well supplied",
     0x0L,
     AC_CAVALRY,
     1, 30, 30, 18, 300L, 450L, 225L, 14, 11,
     MM_EQUINE | MM_WARRIOR | MM_CAPTAIN, 0x0L, 0x0L },
  {"Catapults", "cat", "cplt",
     "Powerful catapults are useful in or about fortified positions",
     UP_BALLISTICS | UP_COVERBONUS | UP_SAPPERUNIT,
     AC_UNIQUE,
     500, -20, -20, 5, 800L, 600L, 250L, 16, 10,
     0x0L, 0x0L, 0x0L },
  {"Siege_Engs", "sge", "sieg",
     "Troop platforms and battering rams, useful in assaulting fortifications",
     UP_FORTDAMAGE | UP_COVERBONUS | UP_SAPPERUNIT,
     AC_UNIQUE,
     400, -20, -20, 5, 800L, 600L, 250L, 18, 10,
     0x0L, 0x0L, 0x0L },
  {"Rocs", "Roc", "Roc",
     "Riding large powerful birds, soldiers make excellent support units",
     UP_FLIGHT | UP_ARROWWEAK,
     AC_UNIQUE,
     1, 20, 30, 10, 300L, 600L, 250L, 13, 10,
     MM_AVIAN | MM_WARRIOR, 0x0L, 0x0L },
  {"Knights", "Kni", "Kngt",
     "Heavily armored and supplied, lords on horseback make good fighters",
     UP_ARROWWEAK,
     AC_CAVALRY,
     1, 40, 40, 20, 600L, 600L, 250L, 15, 12,
     MM_ARMOR | MM_EQUINE | MM_WARLORD | MM_WARRIOR | MM_CAPTAIN, 0x0L, 0x0L },
  {"Griffons", "Grif", "Grfn",
     "Highly skilled aerial troops are a formidable weapon",
     UP_FLIGHT | UP_ARROWWEAK,
     AC_UNIQUE,
     1, 40, 50, 15, 400L, 800L, 250L, 15, 10,
     MM_AVIAN | MM_WARRIOR | MM_CAPTAIN | MM_WARLORD, 0x0L, 0x0L },
  {"Elephants", "ele", "elpnt",
     "Large powerful beasts create a fearsome mobile force",
     0x0L,
     AC_UNIQUE,
     1, 50, 50, 5, 600L, 600L, 250L, 20, 13,
     0x0L, MC_DERVISH, 0x0L },
  {"Engineers", "Eng", "Engr",
     "Engineers skilled at building things, or even destroying them",
     UP_FORTDAMAGE | UP_SAPPERUNIT,
     AC_UNIQUE,
     1, 10, 10, 8, 500L, 500L, 200L, 13, 25,
     0x0L, 0x0L, 0x0L },
  {"Ghosts", "Gho", "@Ghst",
     "The spirits of undead creatures, ghosts can still entrap living souls",
     UP_UNDEAD | UP_FREESUPPLY | UP_ANYDISB | UP_NODRAFT,
     AC_UNIQUE,
     1, -55, -55, 5, 100L, 100L, 0L, 2, 1,
     0x0L, 0x0L, MW_VAMPIRE },
  {"Skeletons", "Ske", "%Sktn",
     "Walking bones, these units are frightful by their actions",
     UP_UNDEAD | UP_FREESUPPLY | UP_DECAY | UP_ANYDISB | UP_NODRAFT,
     AC_UNIQUE,
     1, -35, -35, 5, 100L, 100L, 0L, 6, 3,
     0x0L, 0x0L, MW_VAMPIRE },
  {"Zombies", "zom", "zomb",
     "Undead, and able to absorb losses, such units chill enemy troops",
     UP_UNDEAD | UP_FREESUPPLY | UP_DECAY | UP_ANYDISB,
     AC_UNIQUE,
     1, -25, -25, 5, 100L, 100L, 0L, 8, 2,
     0x0L, 0x0L, MW_VAMPIRE },
  {"Scout", "Scout", "1Sct",
     "Not skilled enough to provide detail, scouts still give useful info",
     UP_SLIPPERY | UP_FREESUPPLY | UP_ANYDISB,
     AC_SCOUT,
     1, -30, -30, 10, 0L, 100L, 100L, 0, 10,
     0x0L, 0x0L, 0x0L },
  {"Spy", "Spy", "2Spy",
     "Specialy trained scouts, skilled in surveillance tactics",
     UP_SIGHT | UP_SLIPPERY | UP_SPCLTRAIN | UP_ANYDISB,
     AC_SCOUT,
     1, -30, -30, 10, 0L, 10000L, 2000L - ARMYUNITCOST, 0, 10,
     0x0L, 0x0L, 0x0L },
  {"Cavalry Scout", "CScout", "3CSct",
     "Mounted scouts provide even swifter surveillance",
     UP_SLIPPERY | UP_FREESUPPLY | UP_ANYDISB,
     AC_SCOUT,
     1, -15, -15, 20, 150L, 1000L, 1000L, 0, 10,
     MM_EQUINE, 0x0L, 0x0L },
  {"Winged Scout", "WScout", "4WSct",
     "Flying scouts provide the swifted and most maneuverable informants",
     UP_SLIPPERY | UP_FREESUPPLY | UP_FLIGHT | UP_ANYDISB,
     AC_SCOUT,
     1, 0, 0, 20, 200L, 1500L, 1500L, 0, 10,
     MM_AVIAN, 0x0L, 0x0L },
  {"Mounted Spy", "MSpy", "5MSpy",
     "A spy on horseback.  What a bargain!",
     UP_SIGHT | UP_SLIPPERY | UP_SPCLTRAIN | UP_ANYDISB,
     AC_SCOUT,
     1, -20, -20, 20, 0L, 15000L, 3000L - ARMYUNITCOST, 0, 10,
     MM_EQUINE, 0x0L, 0x0L },
  {"Winged Spy", "WSpy", "6WSpy",
     "A spy on riding on a winged steed.  Can't be beat!",
     UP_SIGHT | UP_SLIPPERY | UP_SPCLTRAIN | UP_FLIGHT | UP_ANYDISB,
     AC_SCOUT,
     1, -10, -10, 20, 0L, 20000L, 4000L - ARMYUNITCOST, 0, 10,
     MM_AVIAN, 0x0L, 0x0L },
  {"Informant", "Inform", "7Infmt",
     "Well paid informants provide some views of neighbor's lands",
     UP_PAYOFF | UP_SLIPPERY | UP_ENLISTAWAY | UP_ANYDISB,
     AC_AGENT,
     1, -30, -30, 5, 0L, 6000L, 2000L - ARMYUNITCOST, 0, 5,
     0x0L, 0x0L, 0x0L },
  {"Agent", "Agent", "8Agnt",
     "Very well paid agents provide much needed information",
     UP_PAYOFF | UP_SIGHT | UP_SLIPPERY | UP_SPCLTRAIN |
       UP_ENLISTAWAY | UP_ANYDISB,
     AC_AGENT,
     1, -30, -30, 5, 0L, 60000L, 30000L - ARMYUNITCOST, 0, 5,
     0x0L, 0x0L, 0x0L },
  {"Surveyor", "Srvyr", "0Srvyr",
     "A highly skilled scout and land evaluation expert",
     UP_SIGHT | UP_SLIPPERY | UP_SPCLTRAIN | UP_MAPPING,
     AC_SCOUT,
     1, -30, -30, 4, 0L, 10000L, 5000L - ARMYUNITCOST, 750, 10,
     0x0L, 0x0L, 0x0L }
};

/* Traits of the units -- defines in armyX.h */
char *traits_list[] = {
  "Ruler", "Slippery", "Flight", "Undead", "Anti-Air", "Balistics",
  "Beachhead", "Assault", "Sight", "NeedMin", "Damaging",
  "Arrowweak", "Payoff", "Coverbonus", "Disb-Always",
  "1/2-Recruits", "Trained", "Fire", "Water", "Earth",
  "Free-Support", "Decays", "Spellcaster", "Fullcaster",
  "Remote-Enlist", "Sapper", "Mapping", "Nodraft"
};

/* List of the army classes -- definitions in armyX.h */
char *ainfo_clist[] = {
  "Leader", "Caster", "Monster", "Normal", "Scout", "Agent",
  "Merc", "Cavalry", "Sailors", "Orcish", "Archers", "Unique"
};

/* the list of naval classes */
NINFO_STRUCT ninfo_list[NSHP_NUMBER] = {
  { "Warship", "w", 30, NAVY_HOLD,
      20000L, 1000L, 95 },
  { "Merchants", "m", 20, NAVY_HOLD,
      25000L, 1500L, 50 },
  { "Galleys", "g", 25, NAVY_HOLD,
      22000L, 1100L, 75 },
  { "Barges", "b", 10, NAVY_HOLD,
      18000L, 500L, 75 }
};

/* definition of army statuses */
STATUS_STRUCT stat_info[] = {
  { "Sortie", "Sortie", "Attack", 1,
      SPST_ATT | SPST_UNCOMB | SPST_UNSWITCH | SPST_UNMOVE |
	SPST_SIEGED | SPST_SPLYINSECT | SPST_RISKY | SPST_ASTATUS,
	50, 20 },
  { "Ambush", "Ambush", "Ambush", 1,
      SPST_ATT | SPST_HIDDEN | SPST_UNMOVE | SPST_SORTIE |
	SPST_GROUNDED | SPST_SPLYINSECT | SPST_USABLE | SPST_ASTATUS,
      30, 30 },
  { "Attack", "Att", "attack", 1,
      SPST_ATT | SPST_CAPT | SPST_USABLE | SPST_ASTATUS | SPST_NSTATUS,
      20, 0 },
  { "Engage", "Eng", "Engage", 1,
      SPST_ATT | SPST_CAPT | SPST_DIST | SPST_UNMOVE |
	SPST_FORT | SPST_USABLE | SPST_ASTATUS | SPST_NSTATUS,
      20, 0 },
  { "Defend", "Dfd", "defend", 1,
      SPST_USABLE | SPST_ASTATUS,
      0, 20 },
  { "Garrison", "Grsn", "garrison", 1,
      SPST_UNMOVE | SPST_FORT | SPST_SIEGED | SPST_SORTIE |
	SPST_HOLDIT | SPST_USABLE | SPST_ASTATUS,
      0, 30 },
  { "Onboard", "Onbrd", "Onboard", 1,
      SPST_UNCOMB | SPST_NOLIKE | SPST_UNSWITCH | SPST_UNSPLIT | SPST_ONSHIP |
	SPST_UNMOVE | SPST_NOHOLD | SPST_SPLYINSECT | SPST_DIESLAST |
	SPST_NOCAST | SPST_ASTATUS | SPST_VSTATUS,
      0, 30 },
  { "Siege", "Siege", "Lay Siege", 1,
      SPST_CAPT | SPST_UNMOVE | SPST_USABLE | SPST_ASTATUS,
      0, 20 },
  { "Grouped", "Grp", "Group", 1,
      SPST_UNSWITCH | SPST_NOCAST | SPST_ASTATUS,
      0, 0 },
  { "Sieged", "Sieged", "Sieged", 1,
      SPST_SIEGED | SPST_SORTIE | SPST_UNSWITCH | SPST_UNMOVE |
	SPST_UNCOMB | SPST_HOLDIT | SPST_FORT | SPST_SPLYINSECT |
	SPST_ASTATUS | SPST_NSTATUS | SPST_VSTATUS,
      0, -20 },
  { "Reserve", "Resrv", "Reserve", 1,
      SPST_SORTIE | SPST_UNMOVE | SPST_FORT | SPST_HOLDIT |
	SPST_DIESLAST | SPST_USABLE | SPST_ASTATUS,
      0, 0 },
  { "Sweep", "Swp", "Sweep", 2,
      SPST_ATT | SPST_CAPT | SPST_SWEEP | SPST_USABLE | SPST_ASTATUS,
      0, 0 },
  { "WorkCrew", "Wcrew", "Wcrew", 2,
      SPST_SIEGED | SPST_FORT | SPST_UNMOVE | SPST_UNCOMB | SPST_NOCAST |
	SPST_NOLIKE | SPST_UNSPLIT | SPST_UNSWITCH | SPST_ITEMINFO |
	SPST_ASTATUS | SPST_NSTATUS,
      0, -40 },
  { "Traded", "Trade", "Trade", 1,
      SPST_SIEGED | SPST_FORT | SPST_UNMOVE | SPST_UNCOMB | SPST_NOCAST |
	SPST_NOLIKE | SPST_UNSPLIT | SPST_UNSWITCH | SPST_ITEMINFO |
	SPST_ASTATUS | SPST_NSTATUS | SPST_VSTATUS,
      0, 0 },
  { "Carry", "Car", "Carry", 1,
      SPST_USABLE | SPST_NSTATUS | SPST_VSTATUS,
      10, 10 },
  { "Lure", "Lur", "Lure",  1,
      SPST_DECOY | SPST_USABLE | SPST_NSTATUS | SPST_VSTATUS,
      0, 20 },
  { "Support", "Sup", "Support", 3,
      SPST_SUPPLY | SPST_USABLE | SPST_NSTATUS | SPST_VSTATUS,
      0, 0 },
  { "Repair", "Rpr", "Repair", 1,
      SPST_UNMOVE | SPST_UNSWITCH | SPST_UNCOMB | SPST_NSTATUS |
	SPST_VSTATUS,
      0, -30 },
  { "Onbrd Sppt", "ObS", "OnbSppt", 1,
      SPST_UNCOMB | SPST_NOLIKE | SPST_UNSWITCH | SPST_UNSPLIT |
	SPST_SUPPLY | SPST_UNMOVE | SPST_SPLYINSECT | SPST_ONSHIP |
	SPST_VSTATUS,
      0, 20 },
  { "Self Sppt", "SSp", "SelfSppt", 4,
      SPST_SSUPPLY | SPST_USABLE | SPST_NSTATUS | SPST_VSTATUS,
      0, 0 },
  { "OnbSelfSppt", "OSS", "OnbSSppt", 1,
      SPST_UNCOMB | SPST_NOLIKE | SPST_UNSWITCH | SPST_UNSPLIT |
	SPST_SUPPLY | SPST_UNMOVE | SPST_SPLYINSECT | SPST_ONSHIP |
	SPST_VSTATUS | SPST_SSUPPLY,
      0, 20 },
  { "Rover", "Rvr", "Rover", 3,
      SPST_ROVER | SPST_ASTATUS | SPST_CAPT | SPST_ATT | SPST_USABLE,
      10, 0 }
};

/* the sizing information */
int num_armytypes = (sizeof(ainfo_list) / sizeof(AINFO_STRUCT));
int num_atraits = (sizeof(traits_list) / sizeof(char *));
int num_aclasses = (sizeof(ainfo_clist) / sizeof(char *)); 
int num_statuses = (sizeof(stat_info) / sizeof(STATUS_STRUCT));
