/* This file is simply an extension of dataX.c and contains magical data */
/* conquer : Copyright (c) 1992 by Ed Barlow and Adam Bryant
 *
 * A good deal of time and effort has gone into the writing of this
 * code and it is our hope that you respect this.  We give permission
 * to alter the code, but not to redistribute modified versions of the
 * code without our explicit permission.  If you do modify the code,
 * please document the changes made, and send us a copy, so that all
 * people may have it.  The code, to the best of our knowledge, works
 * well, but there will probably always be a need for bug fixes and
 * improvements.  We disclaim any responsibility for the codes'
 * actions.  [Use at your own risk].  This notice is just our way of
 * saying, "Happy gaming!", while making an effort to not get sued in
 * the process.
 *                           Ed Barlow, Adam Bryant
 */
#define DATA_DECLARE
#include "dataX.h"
#undef DATA_DECLARE
#include "butesX.h"
#include "magicX.h"
#include "spellsX.h"

/* The list of military magic powers -- defines in magicX.h */
MAGIC_STRUCT milpow_list[] = {
  { "Archery",
      "The national military gains skill with bows and arrows",
      "Deter air attacks; some unit types vulnerable; +5 attack; +10 defense",
      BUTE_REPUTATION, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Armor",
      "Better skill at metallurgy provides more protections for troops",
      "National move down 2; +10 to defense",
      BUTE_REPUTATION, 5, 0x0L,
      0x0L, MC_METALCRAFT, 0x0L },
  { "Avian",
      "Animal recruiters score success in gaining feathered steeds",
      "Increase national movement rate by 4",
      BUTE_COMMRANGE, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Captain",
      "Increased military discipline provides more skilled fighters",
      "Additional 10% to both attack and defense; Reduced drafting costs",
      BUTE_MORALE, 5, 0x0L,
      MM_WARRIOR, 0x0L, 0x0L },
  { "Dragon",
      "Great skill at demon conjuring provides control over powerful monsters",
      "Even the most powerful monsters might join nation",
      BUTE_TERROR, 10, 0x0L,
      MM_ORC + MM_OGRE, 0x0L, 0x0L },
  { "Equine",
      "The ability to make use of horses provides mobile troops and scouts",
      "Increase movement ability by 4",
      BUTE_COMMRANGE, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Ninja",
      "Elite training provides skilled scouts, spys, and assassins",
      "+5 to attack bonuses",
      BUTE_REPUTATION, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Ogre",
      "Increased demonic studies provides greater control over monsters",
      "Medium strength monsters might join national cause",
      BUTE_TERROR, 8, 0x0L,
      MM_ORC, 0x0L, 0x0L },
  { "Orc",
      "Control over orcish forces gives an increased supply of cannon fodder",
      "Smaller monsters might rally to national cause",
      BUTE_TERROR, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Sapper",
      "Engineering prowess allows better, cheaper siege engines",
      "+10 to defense; More easily produce siege engines and catapults",
      BUTE_METALWORK, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Warlord",
      "Masterful strategists and tacticians increase combat efficiency",
      "+10 to both attack and defense; decrease enlistment expenses",
      BUTE_MORALE, 5, 0x0L,
      MM_WARRIOR + MM_CAPTAIN, 0x0L, 0x0L },
  { "Warrior",
      "Skilled training and battle ready troops increase military prowess",
      "+10 to both attack and defense; decrease enlistment expenses",
      BUTE_MORALE, 5, 0x0L,
      0x0L, 0x0L, 0x0L }
};

/* the list of civilian magical powers -- defines in magicX.h */
MAGIC_STRUCT civpow_list[] = {
  { "Accountant",
      "Governmental officials actually learn addition, increasing revenue",
      "Increase tax revenue by 20%",
      BUTE_CURRENCY, 1, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Amphibian",
      "The ability to survive in hostile watery environments is achieved",
      "Gain ability to survive in jungle and swamp sectors",
      BUTE_HEALTH, 10, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Architect",
      "Playing with Legos(tm) as a kid proves fruitful in the building biz",
      "Decrease building costs and material expenditure by 20%",
      BUTE_REPUTATION, 10, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Botany",
      "Talking to and caring for flowers provides a wealth of knowledge",
      "Improve food and  wood production potential in each sector by 1",
      BUTE_KNOWLEDGE, 5, 0x0L,
      0x0L, MC_FARMING, 0x0L },
  { "Breeder",
      "Skilled mate selection within nation increases desired racial skills",
      "Increase reproductivity by 2%; Decrease attack and defense by 5%",
      BUTE_HEALTH, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Democracy",
      "Public elections provides the population with a greater sense of worth",
      "+2 to move; +10 to combat; +1 to repro; More revolts; Eat more food",
      BUTE_POPULARITY, 10, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Dervish",
      "Nomadic tribes join population and teach nation how to live in sand",
      "Added ability to survive in desert and ice sectors",
      BUTE_HEALTH, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Farming",
      "Skill with cultivating the land increases food production ability",
      "Increase overall food production by 20%",
      BUTE_NUMBER, 0, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Jeweler",
      "Skilled gem and jewel cutters increase value of produced jewels",
      "All jewel expenses decreased by 20%",
      BUTE_JEWELWORK, 10, 0x0L,
      0x0L, MC_MINER, 0x0L },
  { "Marine",
      "Excellent navigational skills increase naval skills",
      "Naval expenses reduced by 20%; Ship speeds increased by 20%",
      BUTE_REPUTATION, 5, 0x0L,
      0x0L, MC_SAILOR, 0x0L },
  { "Metalcraft",
      "Metalurgists increase functionality of metal supply",
      "Decrease all national metal expenditures by 20%",
      BUTE_METALWORK, 10, 0x0L,
      0x0L, MC_MINER, 0x0L },
  { "Miner",
      "Skill at locating deposits increases metal and jewel production",
      "Increase jewel and metal production by 20%",
      BUTE_MINING, 10, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Religion",
      "National unity is acheived by rallying around one doctrine",
      "Increase population reproduction by 2%; Decrease revolt chances",
      BUTE_POPULARITY, 10, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Roads",
      "Skill at building paved land routes increases ability to move about",
      "Increase national communication rate; Increase movement by 4",
      BUTE_COMMRANGE, 10, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Sailor",
      "Prowess at telling tall tales increases desire of youth to be at sea",
      "Decrease naval expenses by 20%; Increase ship speed by 20%",
      BUTE_NUMBER, 0, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Slaver",
      "The use of captured civilians as laborers causes more to be taken",
      "Increase percentage of civlians captured; Increase population unrest",
      BUTE_POPULARITY, -5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Socialism",
      "Sharing more of the wealth among the masses leads to national focus?",
      "Repro rate up by 1%; Take 10% more revenue for health care",
      BUTE_POPULARITY, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Urban",
      "An unaccountable liking to living near cities",
      "Increase national reproduction rate by 2%; Cities are more attractive",
      BUTE_HEALTH, -5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Woodcraft",
      "Skilled woodcutting leads to more productive lumber use",
      "National wood expenditures decreased by 20%",
      BUTE_KNOWLEDGE, 5, 0x0L,
      0x0L, MC_FARMING | MC_BOTANY, 0x0L }
};

/* the list of wizardry magical powers -- defines in magicX.h */
MAGIC_STRUCT wizpow_list[] = {
  { "Alchemy",
      "Magical chemistry leads to molecular transmogrification",
      "Spells allow raw materials to be changed to other raw materials",
      BUTE_KNOWLEDGE, 5, 0x0L,
      0x0L, 0x0L, MW_WYZARD },
  { "Air",
      "Control of the element of Air expands magical abilities",
      "Monster summoning and spell castings are enhanced",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Destroyer",
      "Lack of local Greenpeace chapter has interesting environmental impact",
      "Dervish Power; Sectors near capital are slowly changed to a desert",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Druidism",
      "A penchant for white robes in the woods increases firewood production",
      "Increase wood production ability by 20%",
      BUTE_KNOWLEDGE, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Earth",
      "Skill in manipulation of Earthly elements increases magical ability",
      "Greater understanding of the soil increases food production by 10%",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Fire",
      "Rampant pyromania leads to greater understanding of Promotheus's gift",
      "More resistent to fire attacks within combat",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Hidden",
      "Skill with shadowweaving gives military ability to avoid spying",
      "Military units become uncountable by most nations",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, MW_ILLUSION },
  { "Illusion",
      "Deceptive magic causes watchers to miscount your troops",
      "Double uncertainty of troops and sector values as seen by others",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Know All",
      "Increase mental powers allow visions of all of the surrounding land",
      "The entire map of the world becomes visible",
      BUTE_KNOWLEDGE, 15, 0x0L,
      0x0L, 0x0L, MW_VISION | MW_SEEALL },
  { "See All",
      "Magically enhanced mental powers allow nation to see through illusions",
      "Clearly view enemy troops and sectors, even if hidden",
      BUTE_KNOWLEDGE, 10, 0x0L,
      0x0L, 0x0L, MW_VISION },
  { "Sending",
      "The ability to relocate objects can prove to be a devastating weapon",
      "Ability to relocate troops or monsters at will",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, MW_WYZARD | MW_SORCERER },
  { "Sorcerer",
      "Magical prowess earns highest respect among wizardly peers",
      "Increase magical and spell ability",
      BUTE_SPELLPTS, 10, 0x0L,
      0x0L, 0x0L, MW_WYZARD },
  { "Summon",
      "The ability to call monsters to you increases military power",
      "Bring monsters of many kinds into national ranks",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, MW_WYZARD | MW_SORCERER },
  { "The Void",
      "The ultimate in deception, the ability to cloak troops and land",
      "All troops and sector potentials becomes invisible to most nations",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, MW_ILLUSION | MW_HIDDEN },
  { "Vampire",
      "The lust for blood provides impressive control over the undead",
      "Undead troops bring enemy dead into national ranks",
      BUTE_TERROR, 15, 0x0L,
      0x0L, 0x0L, 0x0 },
  { "Vision",
      "Enhanced mental sight gives greater clarity of surroundings",
      "Counteract deceptive illusions with magic of own",
      BUTE_KNOWLEDGE, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Water",
      "A greater understanding of Aqua enhances magical skills",
      "Ship speeds increase by 20%, invulnerable to storms at sea",
      BUTE_WIZSKILL, 5, 0x0L,
      0x0L, 0x0L, 0x0L },
  { "Weather",
      "A stint as a Junior Weatherwatcher leads to new magical insights",
      "The natural elements have less of an affect on nation",
      BUTE_KNOWLEDGE, 5, 0x0L,
      0x0L, 0x0L, MW_WYZARD },
  { "Wyzard",
      "Magical studies increase skill of nation's wizards",
      "Improved magical powers and abilities",
      BUTE_SPELLPTS, 5, 0x0L,
      0x0L, 0x0L, 0x0L }
};

/* Now the magic class descriptions */
MCLASS_STRUCT mclass_list[MAG_NUMBER] = {
  { "Military",
      sizeof(milpow_list)/sizeof(MAGIC_STRUCT),
      milpow_list },
  { "Civilian",
      sizeof(civpow_list)/sizeof(MAGIC_STRUCT),
      civpow_list },
  { "Wizardry",
      sizeof(wizpow_list)/sizeof(MAGIC_STRUCT),
      wizpow_list }
};

/* The information on all of the spells
 *
 *  The list of different spell classes is:
 *      O = Offensive combat spell
 *      D = Defensive combat spell
 *      U = Spell to affect a military unit
 *      u = Spell to affect only an army unit
 *      L = Spell to affect only a leader unit
 *      S = Spell to affect the current sector
 *      M = Spell to affect a monster unit
 *      R = Raw materials are affected
 *
 *  Cost in spell points to cast the spells; For those
 *  of type U, the cost is men affected per spell point
 *
 * Defines are in the file spellsX.h.
 */
SPELL_STRUCT spell_list[] = {
  { "Enhance", "Enhance",
      "Enhance the combat ability of a unit",
      "A silver glow envelopes the %s, then slowly fades away",
      "A glint of silver shows in the air, but nothing else happens",
      1, 'U',
      SI_ANYCAST,
      300, 5, 95,
      0x0L, 0x0L, 0x0L },
  { "Flight", "Flight",
      "Enable a unit to fly for one movement phase",
      "The %s begins to float just above the ground",
      "Some dust in the area swirls upward; the spell appears to have failed",
      1, 'u',
      SI_SPELLCASTER,
      100, 10, 80,
      0x0L, 0x0L, MW_AIR },
  { "Heal", "Heal",
      "Restore the strength of a military unit",
      "A glow surrounds the %s, and health is greatly improved",
      "A small bird got in the way and was healed",
      1, 'u',
      SI_NONMONSTER,
      300, 3, 98,
      0x0L, 0x0L, 0x0L },
  { "Quake", "Quake",
      "Cause an earthquake to shake the current sector",
      "A slow deep rumble begins far under the surface of the Earth",
      "The Earth, offended by the spell, knocks your leader to the ground",
      1, 'S',
      SI_FULLCASTER,
      25, 80, 50,
      0x0L, 0x0L, MW_SORCERER | MW_WYZARD | MW_EARTH },
  { "Send", "Send",
      "Summon and send a monster against an enemy nation",
      "A %s materializes before your eyes, demanding to know your enemy",
      "A puff of smoke swirls up, fades, and shows a parakeet which flys away",
      1, 'M',
      SI_FULLCASTER | SI_NONMONSTER,
      2, 30, 75,
      0x0L, 0x0L, MW_SUMMON | MW_SENDING },
  { "Scare", "SCare",
      "Attempt to frighten civilians into leaving the sector",
      "The surrounding area shimmers, and gains a rather menacing appearance",
      "A shimmer blurs your vision, but there is no longlasting affect",
      2, 'S',
      SI_ANYCAST,
      10, 10, 80,
      0x0L, 0x0L, MW_ILLUSION },
  { "Summon", "SuMmon",
      "Summon a monster to serve within the nations military",
      "A cloud of smokes billows up, encircling a newly appeared %s",
      "A small cloud of smoke billows up, revealing a newly summoned parakeet",
      3, 'M',
      SI_SPELLCASTER,
      1, 20, 85,
      0x0L, 0x0L, MW_SUMMON },
  { "Teleport", "Teleport",
      "Instantly transport a unit to another sector",
      "A clear focus upon the %s is gained, and the spell is a success",
      "Your leader loses concentration and the power of the spell fades",
      1, 'u',
      SI_SPELLCASTER,
      20, 50, 65,
      0x0L, 0x0L, MW_SENDING },
  { "Transmute", "TRansmute",
      "Alter the physical makeup of raw materials",
      "You touch the %s, and %d %s appear before your eyes",
      "All of the raw material is consumed in flash of energy",
      2, 'R',
      SI_SPELLCASTER | SI_NONMONSTER,
      10, 70, 80,
      0x0L, 0x0L, MW_ALCHEMY },
  { "Transfer", "Xfer",
      "Transfer all the magical energy of one leader into another",
      "As your %s is touched, there is a noticable increase in power",
      "Hmmm.... it didn't seem to work",
      1, 'L',
      SI_NONMONSTER,
      0, 10, 99,
      0x0L, 0x0L, 0x0L }
};

/* sizings */
int spell_number = (sizeof(spell_list)/sizeof(SPELL_STRUCT));
