#	conquer: Copyright (c) 1991 by Edward M Barlow and Adam Bryant
#		 All Rights Reserved
#
#	This Makefile should not need changing.
#
#	Please report any problems that you encounter with any of the
#	Makefiles.  If any problems develop while compiling, or if any
#	files but the Makefiles and header.h files need editing,
#	please send me mail.
#			adb@cs.bu.edu
#			adb@bucsf.bu.edu
#       		adb@bu.edu
#

#	All of the default settings
MAKE	= %%MAKE%%
MKDPND	= %%MKDPND%%
MKDIR	= %%MKDIR%%
SHELL	= %%SHELL%%
CD	= %%CD%%
CC	= %%CC%%
RM      = %%RM%%
CP	= %%CP%%
MV	= %%MV%%
ECHO	= %%ECHO%%
STRIP	= %%STRIP%%
NULL	= %%NULL%%
TOUCH	= %%TOUCH%%
CHOWN	= %%CHOWN%%
CHMOD	= %%CHMOD%%
LIBS	= %%LIBS%%
SYSFLG	= %%SYSFLG%%
CFLAGS	= %%CFLAGS%%
TOPDIR	= %%TOPDIR%%
DATADIR	= %%DATADIR%%
BINDIR	= %%BINDIR%%
INCDIR	= %%TOPDIR%%/%%INCDIR%%
SRCDIR	= %%TOPDIR%%/%%SRCDIR%%
AUXDIR	= %%TOPDIR%%/%%AUXDIR%%
DOCDIR	= %%TOPDIR%%/%%DOCDIR%%
CQUER	= %%CQUER%%
CQRUN	= %%CQRUN%%
CQSORT	= %%CQSORT%%
CXTRACT	= %%CXTRACT%%
GFILS	= %%GFILS%%
AFILS	= %%AFILS%%
XFILS	= %%XFILS%%
GOBJS	= %%GOBJS%%
AOBJS	= %%AOBJS%%
XOBJS	= %%XOBJS%%
NROFF	= %%NROFF%%
TROFF	= %%TROFF%%

#
#	Building and Installation Procedures
#
all:	
	@${ECHO} "Use one of:"
	@${ECHO} "   make build       -- build everything"
	@${ECHO} "   make install     -- install everything"
	@${ECHO} "   make clean       -- clean up some files"
	@${ECHO} "   make clobber     -- clean up all files"

#
build:
	@${ECHO} "Build in Doc complete"

#
install:	indocs
	@${ECHO} "Install in Doc complete"

#	Cleaning things up
clean:
	${RM} *.o *~ *.bak \#* ${NULL}

#	Really clean things up
clobber:	clean clobber2
	${RM} ${NCONV} indocs ${NULL}

#
#	Makefile specific variables
#

#	Name of the program to properly convert the nroff output
NCONV	= ./ezconv

#	List of source files for documentation
DSRC	= Helpfiles.nr Overview.nr Functions.nr Display.nr \
Sectors.nr Nations.nr Economics.nr Movement.nr Warfare.nr \
Powers.nr Xchanges.nr Beginnings.nr God-Powers.nr Customize.nr \
Quickies.nr Version.nr

#	List of output files for hardcopy build
DHRD	= Conquer-Doc.ps

#	List of output files for online build
DONL	= ${DSRC:.nr=.doc}
# === BROKEN MAKE ===
#	(note: bad makes need this)
#DONL	= Helpfiles.doc Overview.doc Functions.doc Display.doc \
#Sectors.doc Nations.doc Economics.doc Movement.doc Warfare.doc \
#Powers.doc Xchanges.doc Beginnings.doc God-Powers.doc Customize.doc \
#Quickies.doc Version.doc

#	List of dependencies for installation
#	[if you do not have nroff, comment this out]
INDOCS	= ${DONL}

#	Add to the suffixes list
.SUFFIXES:	.nr .doc .ps

#
#	Makefile specific rules and building information
#
online:	${DONL}
	@${ECHO} "== Online Documentation Updated =="

hardcopy:	${DHRD}
	@${ECHO} "== Hardcopy Documentation Updated =="

docs:	${NCONV} online hardcopy

indocs:	${DONL}
	-${MKDIR} ${DATADIR}
	${CHOWN} ${DATADIR}
	${CHMOD} 700 ${DATADIR}
	${CP} ${INDOCS} ${DATADIR}
	${CHOWN} ${DATADIR}/*
	${TOUCH} indocs

clobber2:
	${RM} ${DONL} ${DHRD} ${NULL}

#
#	how to create each of the online documents
.nr.doc:	$<
	${NROFF} roff-mac.nr $*.nr | ${NCONV} > $*.doc

#
#	how to create the postscript documents
.nr.ps:	$<
	${TROFF} $*.nr > $*.ps

#
#	quick conversion program
${NCONV}:	${NCONV}.c
	${CC} -O ${SYSFLG} -o ${NCONV} ${NCONV}.c
	${STRIP} ${NCONV}

#
#	additional dependencies
${DONL}:	roff-mac.nr ${NCONV}
#
${DHRD}:	roff-mac.nr ${DSRC}
#
build:	${DONL} ${DHRD}
#
