.CH "Charts and Summaries"
.CS "Things to Come"
.PP
This section has yet to be written, but should appear in the next
patch.  Please get back to me listing all of the things that you feel
should be listed in a "quick" summary of information.
.PP
The things I currently plan:  concise army listing, vegetations,
contours, navy information, caravan information, designations,
tradegoods, constructions, nation types, racial information, function
summaries for all of the keymaps.
.CE
