.CH "Military Units and Combat"
.CS "Warfare in Conquer"
.PP
While the backbone of a nation in Conquer is its economy, the survival
and growth of the nation is even more dependent upon its military.
Because, sooner or later, a conflict involving the nation will develop
and any losing side may be wiped out of existence.  Thus, it always
comes down to the military skill of the troops and leaders which will
keep a nation alive.
.PP
There are three basic military units within conquer: the armies, the
navies and the caravans.  The navies and caravans provide mostly a
supporting role to the true military might of the armies.  The armies
themselves are composed of many different kinds of units, the three
basic categories being: leaders, monsters, and normal units.
.PP
Conflicts between units will occur when troops from two countries are
in the same sector (or neighboring sectors in some cases), and the
diplomatic status of one of the nations is aggressive enough towards
the other for any of its troops within the sector to attack.
.CE
.CS "Caravans"
.PP
Caravan units provide a land based method for relocating supplies from
one supply center to another.  Much faster than a "chain" of cities,
caravans are able to visit a number of supply centers each turn.
.PP
A caravan consists of wagons grouped in sets of 10 with 3 men acting
as crew for each wagon, for a total of 30 men for a full complement of
wagons.  The monthly supplies needed to support a caravan consist of
the food needed for the crew and a thousand talons per each set of ten
wagons.
.PP
Each caravan can carry civilians and raw materials.  Since all of the
items are grouped together on the same caravan, the amount of space
available for each item is governed by the items already onboard as
well as the size of the materials to be placed on the caravans.  For
each set of wagons the storage capacity is: 50 civilians, 50 thousand
talons, 12.5 thousand jewels, 10 thousand metals, 5 thousand food or
6.25 thousand wood.  Each of these maximums are obtainable if that
material is the only item onboard the caravan.
.PP
The movement ability of the caravans is half of the movement potential
of the nation as a whole (minimum value of 6), and can be increased or
decreased by the speed selection of the unit.
.PP
The combat value of caravans is governed by the number of crew on the
caravan and the combat ability of the nation as a whole.  Due to the
non-combat nature of caravans, they will usually have a combat bonus
penalty of 50.
.CE
.CS "Naval Units"
.PP
Navies provide a method for relocating civilians, armies, caravans and
materials over water sectors and through canals.  A supply network
based on the use of navies can be the swiftest method for getting
materials to various portions of your nation.  And navies are just
about the only method for getting military units across larger bodies
of water.
.PP
Naval units (or fleets) are composed of four different classes of
ships: warships, galleys, merchants, and barges.  Warships are used to
carry armies and to perform combat upon water sectors.  Galleys are
used to transport civilians and also have some combat ability.  The
merchant ships are designed mostly for carrying the various raw
materials across the water.  Finally, the barges are very weak
combatwise, but are the only method available for carrying caravan
wagons over water sectors.
.PP
Each ship class also comes in three different sizes: heavy, medium and
light.  The light ships possess one cargo hold, the medium ships two
and the heavy three.  It is cheaper to construct the larger ships, and
they are better able to handle deeper ocean, but their speed is not up
to that other their smaller counterparts.  The speed of the entire
fleet is that of the slowest member of the fleet.
.RF "Movement" "Unit Relocation"
.PP
Each ship hold is supported by 100 men acting as crew.  The support
cost for each ship hold is based on the ship type: Warships need 1000
talons, Merchants need 1500 talons, Galleys need 1100 talons and
Barges need only 500 talons.  In addition to this funding, food will
need to be provided for the crew.
.PP
Each warship hold is able to carry 100 men; Each galley hold is able
to carry 100 people; Each barge hold is able to transport 20 wagons;
And, finally, each merchant hold is able to transport twice the
materials of 10 wagons:  100k talons, 25k jewels, 20k metals, 10k food
and 12.5k wood.
.PP
Naval vessels are much better equipped for land combat than caravans,
due to their fortified structure, but they are still vulnerable to
army units.  On land, the default combat penalty for navies is 25.  On
the ocean, however, most army troops are at half effectiveness and
thus can be susceptible to naval attack.
.CE
.CS "Army Units"
.PP
The army unit forms the basis of military strength within Conquer.
They are the only units which may capture land and they are also the
only units which may prevent it from being captured.  There are three
basic kinds of army units:  leaders, monsters, and normal soldiers.
.PP
Leaders form the focus of national power.  If a non-leader army unit
is out of communications range of all national leaders, that unit will
only possess half of its potential movement ability.  Other units are
also able to "group" under leaders so that the entire set of units
might act as a whole.  And finally, leaders are the focal point for
the nations magic abilities, as they are the units through which
spells are cast, with special spellcasting leaders being needed to use
the most potent spells in the game.
.RF "Powers" "Magical Powers"
.PP
Monsters are very powerful weapons because a single monster represents
many men in combat strength.  Also, in combat, monsters cannot be
damaged but must be killed outright.  The "damage" they receive in
combat merely indicates the percent chance of their being killed.  If
they are not killed, they will be left totally undamaged.  When
capturing land or being placed onboard a ship, the "size" of the
monster is used instead of the combat strength to indicate their
ability / volume.  Monsters need to be paid in jewels every month, or
they will desert the nation, and possibly turn and attack it in
retaliation.
.PP
Last, but not least, there is the normal soldier.  They form the
backbone of the military, due to their land capturing ability and
variety of skills.  There are soldier types ranging from Archers to
Zombies, including Catapults and Cavalry.  Each type has different
strengths and weaknesses; some possess the ability of flight and
others are skilled at attacking enemy fortifications.  The support
costs vary between the various types, but generally each requires
talons and food to be sustained.
.PP
Anyway, the different army types are broken into a number of classes,
which organize similar types under the same category.  The next
section describes these various army classes.
.CE
.CS "Army Classes"
.PP
There are a number of different army classes.  These classes indicate
those troops which are considered to be similar in nature and thus can
sometimes be upgraded to better units within the same class.  The
descriptions for all of the army classes is:
.IT
Leaders -- Leaders are units who act as the guiding force for the
nation.  They inspire their troops as well as guide them.
.IT
Casters -- A special form of leader, these units serve a nation
through their magical abilities.
.IT
Monsters -- Creatures whose allegiance is often based on greed, such
units are more deadly than many times their number in normal soldiers.
.IT
Normal -- Such soldiers are only distinguished by the skill of their
training and the quality of their weaponry.
.IT
Scouts -- Soldiers whose sole purpose it is to roam beyond the bounds
of the national territory, such units increase the amount of knowledge
a nation possesses through their travels.
.IT
Agents -- Civilians recruited from another nation's population to
provide information about that nation.  To enlist such units, you must
attempt the enlistment in the supply centers of a another nation.
.IT
Mercs -- Soldiers for hire, these unit types have no allegiance except
towards money.  Such units do not drain the metal or recruit resources
of a nation.  The combat ability of these troops is independent of the
nation under which they serve.
.IT
Cavalry -- Soldiers upon horseback, these unit types are the swiftest
land based units.  Their horsebound nature makes them less useful when
attacking fortifications, but frightful when fighting in the open.
.IT
Sailors -- Soldiers born and bread for the seas, these troops are
better suited to being aboard ships than any other.
.IT
Orcish -- Orcish soldiers are trained in ways different from other
troops.  Their inbred fear of their leaders and loathing of their
subordinates keeps them fighting among themselves as well as against
others.
.IT
Archers -- Archers are troops trained in the use of the latest
technological advances: bows, arrows and possibly crossbows.  These
troops are especially useful in garrisons and as defensive troops, but
in some cases can make excellent attacking units.
.IT
Unique -- There are some unit types which cannot be classified with
any other units.  Most specialized troops belong to this category.
.UT
.CE
.CS "The Army Traits"
.PP
There are a number of skills which can be possessed by an army unit,
such as being able to fly or being among the undead.  These traits
will usually indicate a special skill of the unit, and are what really
distinguish the various army types from each other.  The list of
traits and descriptions of each is:
.IT
Ruler -- This unit is not only a national leader, but the chief among
all of the leaders.  Without a Ruler a nation will lose focus and be
unable to move most of their troops.
.IT
Slippery -- Troops skilled in deception and observation, this trait
indicates that a unit of a small enough size will be able to sneak
by an enemy garrison without being stopped.
.IT
Flight -- Some units are capable of self-generated flight.  Such units
can travel over land and even water at a greater rate than other units.
.IT
Undead -- Undead units are frightful in combat, for they can take the
dead from the field and turn them into Zombies.  Normal undead
soldiers can convert a single dead soldier per clash, while undead
monster units can convert as many as 1/7th of their combat strength
and undead leaders up to 1/5th of their experience.
.IT
Anti-Air -- Units with this trait are sometimes able to force enemy
aerial troops passing overhead down from the sky and onto the ground.
.IT
Ballistics -- Ballistic unit types are capable of launching projectile
weapons from their position towards their enemy, increasing their
effectiveness in combat from fortified positions.
.IT
Beachhead -- Units with this trait are capable of disembarking from
naval craft without the guidance of a leader unit.
.IT
Assault -- Only assault troops may disembark from a ship onto
territory owned by a non-Allied nation.
.IT
Sight -- Skill at observation and intrigue enables units with this
trait to view more closely the sectors of another nation.
.IT
Needmin -- Soldiers which must fight as a group will not have their
full combat effectiveness unless they possess the minimum number of
troops necessary to sustain their fighting style.
.IT
Damaging -- Some units are capable of inflicting damage upon enemy
fortifications while attacking them.  If more than fifty percent
damage is inflicted upon the troops inside, the fortifications might
possibly be diminished.
.IT
Arrowweak -- Some units are more susceptible to attack using ballistic
weapons than others.  Such units will receive more damage than normal
if they face a substantial ballistic barrage.
.IT
Payoff -- There are a number of units which must be paid when they are
discharged from service.  Usually this is just "hush money", but often
it is the final payment for services rendered.
.IT
Coverbonus -- Specially designed units allow the increase of combat
ability for the entire attacking or defending force.  For every 300
men in such a unit, 10-20% is added to the attack bonus of the units
fighting by their side.
.IT
Disb-Always -- This trait indicates a unit capable of being disbanded
in any sector, even one not owned by their nation.
.IT
1/2-Recruits -- A unit of this type is not a fully mobilized combat
unit and as such can draw twice the number of volunteers as a normal
army type.  Thus, they only use up half of the recruiting pool
available to the supply center.
.IT
Trained -- This unit requires special training beyond the normal
combat training.  This means that to upgrade a troop of soldiers to
this type of unit will cost more in training expenses.
.IT
Fire -- A unit of type fire is impervious to fire attacks, and is
sometimes capable of making fire based attacks of its own.
.IT
Water -- Borne of water, such a unit is capable of walking across it
without drowning.
.IT
Earth -- A creature of the Earth, this being is capable of tunneling
through many earthen fortifications and even under other
constructions.
.IT
Free-Support -- This trait indicates that a unit type is
self-sustaining and need not be given any supplies in order to
survive.
.IT
Decays -- This trait indicates that the unit will slowly lose combat
effectiveness as time passes.
.IT
Spellcaster -- This unit is capable of casting all of the spells in a
nations' magical arsenal.  While normal leaders are only able to use
moral and healing spells.
.RF "Powers" "Magical Powers"
.IT
Fullcaster -- This unit is capable of weilding the full spell casting
might of a nation, otherwise a spellcasting unit will achieve a
maximum spell point level at half of the national spell point value.
.RF "Powers" "Magical Powers"
.IT
Remote-Enlist -- Some units may be drafted from the population of
enemy supply centers.  To enlist them, a source of supplies must be
near enough to provide the bribery necessary to gain the unit type.
.IT
Sapper -- A sapper unit is a unit which is capable of increased
engineering skill, either in construction or destruction.
.IT
Mapping -- Some units are able to record information onto the national
map, preserving a view of a sector, or perhaps making notes about it.
.IT
Nodraft -- Even if the unit becomes available to the nation through
magical requirments being met, it is still not possible to draft the
unit directly.  Special circumstances will be needed to bring the unit
the realm of control of the nation.
.UT
.CE
.CS "Unit Information"
.PP
For every unit in the current sector, a description of the unit will
be shown.  If there are multiple units within the sector, you can page
through them using the "pick-next" and "pick-previous" commands.
.SB
           >army 205: 75 inf            >Wzrd 1 x=251 p=10
             2 m:45(>) st:Dfd             m:0 sp:- st:Rsrv
.SE
.PP
The above two descriptions are for army units.  The one on the left
is for a normal infantry unit, while the one on the right shows the
national leader.  The first line shows the unit id number, the type of
the unit, and the experience or strength of the unit.  Also,
spellcasting units will have the number of spell points left to the
unit shown.  The `>' will be replaced with another character if the
unit is the currently selected unit.  Usually, a `*' will be used, but
if a leader is a group leader a `+' sign will be shown.  The second
line indicates the number of months worth of supplies the unit
possesses (if they need supplies), the percentage of unit movement
ability left to the unit, the speed of the unit, and the status of the
unit.
.SB
                         >navy 8 w4 m0 g0 b0
                           4 mv:90(<) st:Eng
.SE
.PP
The above description is the similar entry for a naval unit.  The
first line indicates the id number of the navy, and the number of each
ship class in the unit.  The second line indicates the number of
months worth of supplies onboard, the movement potential of the unit,
the speed of the unit and the status of the unit.  As with the armies,
a `*' or a `+' will replace the leading `>' if it is the currently
selected unit, with a `+' indicating that the navy is carrying some
cargo.
.SB
                         >cvn 3 cw:30 wg:100
                           3 mv:50(<) st:Car
.SE
.PP
Finally, an example description of a caravan unit is shown above.  The
first line shows the id number of the caravan, the crew onboard the
caravan and the number of wagons in the caravan.  The second line
indicates the supplies, remaining movement potential, speed and status
of the unit.  A `+' or `*' will also replace the `>' if it is the
currently selected unit, with a `+' indicating that the caravan has
cargo onboard.
.PP
While using god mode, instead of a `+' or a `*' to indicate the
currently selected unit, the nation mark will be shown.  This is to
distinguish the units belonging to different nations from each other.
.CE
.CS "Unit Efficiency"
.PP
The health, or efficiency, of every unit is taken into account as an
integral part of that unit.  When spells are cast, the health of the
spellcaster is taken into account, both in figuring if the unit may
cast spells and if the unit has the strength to cast specific spells.
During combat, the combat bonus of the unit is a direct reflection of
the efficiency of the unit.  And, after the combat or due to
starvation, the health of the unit will be decreased due to the
hardship involved.
.PP
Thus, the "efficiency" of a unit, be it army, navy or caravan, is a
reflection of how healthy a unit is.  For navies and caravans, it is
also an indication of how sturdy the physical materials of the vessel
are.  This efficiency is shown under the military reports as part of
the status of the unit and is indicated as a percentage.
.PP
For most units, the efficiency will range in value from 0% to 100%,
with 100% indicating a fully functional unit.  Normal army units,
however, may have a variable maximum efficiency.  This may be lower
than 100%, indicating inexperienced troops, or up to 150%, indicating
battle hardened veterans.  The value of the maximum efficiency of a
unit, unlike the efficiency value, will not be directly visible to
your nation, since the "potential combat efficiency" of a unit is an
intangible thing.
.CE
.CS "Unit Movement"
.PP
Each unit possess a certain amount of movement potential, governed by
the movement ability of the nation as a whole, as well as the movement
potential of the unit type involved.  In addition, the unit may adjust
its speed in order to move at will.  When moving faster, you can move
farther, but it is also more dangerous to do so.
.PP
There are four basic speeds available to a unit:  not moving, slow,
medium, and fast.  If the unit is not moving, the character `-' is
used to indicate the speed, while the characters `<', `=', and `>'
represent slow, medium, and fast, respectively.  Units garrisoned in
wall sectors have the potential of relocating to any adjacent wall
sectors, so they have a speed indicator of `+' if they are still able
to move.
.PP
Finally, there are a number of different methods for moving a unit.
Many units possess the ability of flight, which is indicated by a `F'
character before the speed value, or by having the speed enclosed in
square brackets instead of parenthesis. Naval units are able to move
across water, but not on land and normal caravans and armies just move
between the land sectors, avoiding water.  Anyway, no matter what the
method used in relocating the unit between sectors, the command
"move-unit" is used to begin the relocation of the unit.
.RF "Movement" "Unit Relocation"
.CE
.CS "Supplying Units"
.PP
As has been mentioned before, unless the campaign is configured
otherwise, each unit will need supplies in order to survive.  If the
supplies run out, so do the troops.  Most units (normal army units,
navies and caravans) will need talons and food, monster units will
need jewels and leader units (and some scouts) can exist without
supplies.
.PP
During each update, all units will consume 1 month worth of supplies.
If the unit is within range of supply centers and not under siege or
within the water, the unit will automatically have the consumed
supplies replenished.  Otherwise, the unit may only receive
replenishment from within the same sector.
.PP
It is possible to manually supply a unit using the "region-command" or
"command-unit" functions.  In order to increase supplies, the unit
must be in land owned by your nation within range of supply centers,
or in a sector where supplies are kept.
.PP
Currently, units are not able to live off of the land, so units must
be supplied, and supplies must come from their own nations resources.
.RF "Economics" "Economic Management"
.CE
.CS "Unit Statuses".
.PP
Each military unit may be assigned a task.  This task can involve guarding
a fortified sector, attacking an enemy or even hiding in ambush
waiting for unwary enemy troops to approach.  The status of the unit
indicates the task which it has been assigned, and the list below
shows all of the available statuses.  An asterisk (*) indicates a
status where the unit is unable to move.
.IT
Sortie* -- Launch a swift attack against enemy troops besieging a
sector.  Only available to army units.
.IT
Ambush* -- Hide out in the sector hoping to launch a surprise attack on
enemy troops.  Only available to army units.
.IT
Attack -- The basic attacking mode.  Not available to caravans.
.IT
Engage* -- Keep your unit within a sector and attack any enemy units
approaching within one sector range.  Not available to caravans.
.IT
Defend -- Have your unit patrol the terrain the sector but do not
initiate combat unless attacked.  Only available to army units.
.IT
Garrison* -- Use a fortified position within the sector and garrison
the sector.  Only available to army units.
.IT
Onboard* -- This status is given to a unit which is being carried in
the cargo hold of a navy.  Not available to navy units.
.IT
Siege* -- Lay siege to the fortified structure within the sector.
This would require odds of two to one or better against troops within
the fortification.  Only available to army units.
.IT
Grouped -- Follow the actions of a given leader.  The status of the
leader is used as the status of the unit.  Only available to army
units.
.IT
Sieged* -- This unit is trapped within the fortifications of the
sector by enemy besieging troops.
.IT
Reserve* -- Keep troops back within the fortifications for later use.
Such troops may only be reached if any gaurding fortified troops
receive 80% or more damage.  Only available to army units.
.IT
Sweep -- Perform an attack against any enemy troops encountered, but
do not attempt to engage fortified troops.  Only available to army
units.
.IT
WorkCrew* -- A unit with this status is engaged in the building of
roads, bridges, canals or other constructions.  Not available to
caravan units.
.IT
Traded* -- A unit with this status has been placed up for sale by its
owner.
.IT
Carry -- Any materials stored on the unit will not be available for
consumption by the national economy.  Not available to army units.
.IT
Lure -- Do not attempt to avoid enemy attackers, thereby attempting to
draw off more of the attacking troops.  Not available to army units.
.IT
Support -- Any materials stored on the unit will be made available for
distribution and comsumption in the national economy.  The unit itself
will only take from the goods for supplies if the supply level is at
one month worth.  Not available to army units.
.IT
Repair* -- The unit is undergoing repair and will not be able to move
until the next update.  Not available to army units.
.IT
Onbrd Sppt* -- This is equivalent to the Onboard status, but also
indicates that the caravan is on Support status.  Only available to
caravan units.
.IT
Self Sppt -- The unit is on Support status, and will also consume what
it is carrying when gathering its own supplies.  This is useful to
maintain naval supply levels during long voyages.  Not available to
army units.
.IT
OnbSelfSppt* -- This is equivalent to being Onboard while having the
Self Sppt status.
.IT
Rover -- An army unit is assigned the task of looking for new land to
capture.  If in an unowned sector, it will stay in place, otherwise it
will move to the sector with the greatest perceived potential within a
one sector radius.  This status forms the backbone of NPC territorial
acquisition and is only available to army units.
.UT
.CE
.CS "Capturing Sectors"
.PP
There are two ways to claim a sector for your nation: taking a sector
which no one one owns or taking a sector away from a nation who you
are at war with.  Only armies with the following statuses may capture
sectors: Attack, Engage, Siege, Sweep, or Rover.  Such army units can
be made up of monsters, leaders or normal soldiers, but the combined
capturing ability of the units must be at least 75 men for an attempt
even to be made.
.PP
The number of men needed to capture a sector is dependent upon the
number of opposing troops within the sector, as well as the number of
civilians within the sector.
.PP
First, if the sector is fortified and there are any troops within the
fortifications, the sector cannot be captured.  Thus, all of the
garrison of a sector must be eliminated before it may be captured.
.PP
Second, if there are any opposing troops within the sector, the odds
must be well in your favor (better than 7 to 1) for them not to
prevent the capturing of the land.  Once these odds have been reached,
only a single soldier will be required to compensate for every
opposing soldier.
.PP
Finally, you will need to subdue the population of the sector.  This
will usually require about 10% of the population of the sector in
soldiers, depending on the sector designation and the race of the
troops.  If the sector being captured is a capital, the required
percentage is tripled; if the sector is a city it is doubled; for
towns and stockades it is increased by 50% and other fortified sectors
have a 20% increase.  A small racial adjustment will then be made to
the final percentage which will then be taken from the total of the
capturing troops.
.PP
So, if, after subduing the population and any opposing troops, there
are still 75 "men" leftover, the sector becomes yours.
.CE
.CS "Results of Sector Capturing"
.PP
When a sector is taken from one nation by another, the civilians
within the sector are bound to suffer.  Thus, if there is a population
within the sector, a portion of those civilians will probably be
killed or captured.  Also, the sector can be damaged just by having
the sector forcefully taken.
.PP
Such damage will generally be reflected by farming sectors losing
their crops and the sector becoming devastated.  In order to rectify
such devastation, the "construct" command will have to be used to
"Undevastate" the sector.  This will usually cost one half of what it
would take to build up the sector from scratch.  Alternatively, the
designation may be changed to another type, with the resulting
conversion process removing any devastation.
.CE
.CS "Combat"
.PP
Combat may take place when units from one nation encounter units from
another nation with whom they are at war.  Only the statuses of
Sortie, Ambush, Attack or Sweep will cause a unit to initiate combat.
.PP
In combat, the troops of each nation are divided into up to five
separate forces of troops:  Sweepers, Attackers, Defenders, Fortified
and Protected.  Combat is initiated by the Sweeping and Attacking
forces which advance through each successive wave of the enemy forces
until the attack is either repelled or has met all of the enemy
forces.  The Sweeping forces will stop after encountering any
Defending forces, since they will avoid hurling themselves against
fortifications.
.PP
Sweeping forces will attack opposing Sweeping, Attacking and Defending
forces in that order.  If they are repelled by any of the forces, they
will not initiate attacks on of the other forces.  Attacking forces
will attack Sweeping, Attacking, Defending, Fortified, and Protected
forces, but must get through each in turn and inflict at least 80%
damage on Fortified troops before they may reach the Protected troops.
.PP
So, a conflict in a sector will be broken down into a number of
separate clashes.  During each clash the number of soldiers per side
will be multiplied by average combat bonus of the soldiers to
determine the odds of the battle.  A dice will be rolled against each
side to determine how much damage that side will take, adjusted by the
odds of the battle.
.PP
For an even one-to-one battle, the dice roll, multiplied by twice
(once for each side) the "Average Combat Damage" and then divided by
100 will give the actual combat damage which a side receives.  With
uneven odds, the "Overmatch Adjustment" multiplied by the odds will be
added to the damage of the lesser side, and subtracted from the damage
of the greater side.  If any result is less than the "Minimum Damage
Limit", it will be limited to being the roll multiplied by the
"Minimum Damage Limit".  All four of these quantities may be
configured by world dieties.
.RF "God Powers" "Conquer God Mode"
.PP
A simplied summary of each clash is: Step 1) figure the odds. Step 2)
compute the damage based on even odds. Step 3) adjust the damage for
each side based on the odds.
.CE
.CS "Figuring Combat Bonuses"
.PP
The key to determining the combat ability of a military unit is its
combat bonus, which is multiplied with the actual strength of the unit
to compute the military prowess of the unit.  There are a number of
factors which come to play in figuring the combat bonus of a unit:
the terrain of the combat, the status of the unit, the combat ability
of the nation and the unit itself.
.PP
Units begin with a base combat bonus of 100, and then have all of the
various adjustments added in.  For navies on land, this usually means
a 25 point reduction.  For caravans, a 50 point reduction.  The rest
of the adjustments are then computed by adding in the unit bonus,
terrain bonus and national bonus.
.PP
There are basically two situations for a unit in combat:  a unit is
attacking, or it is not.  If it is attacking, then it will usually
lose any bonuses associated with the terrain of the sector, and all
bonuses will be figured based on the offensive combat bonuses.
Otherwise, it will receive the bonus associated with the terrain
of the sector, and all other bonuses will be based on the defensive
combat bonuses.  If the unit is fortified, it will also receive the
bonuses associated with the fortifications.
.PP
The national combat bonus will also be added in.  If the unit is
attacking the national attack bonus will be used, otherwise the
national defense bonus will be used.  Of course, if the unit is a
mercenary unit, the mercenary combat bonuses will be used instead of
the national combat bonuses.
.PP
Without a doubt, the most important factor for determining the combat
bonuses is the status and efficiency of the unit.  The status will
determine if attacking or defending bonuses will be used, if
fortification bonuses are to be used, and it will also determine any
additional bonuses due to the status itself.  The efficiency of the
unit comes into play once the combat bonus has been completely
calculated, acting as a multiplier.
.PP
Any army unit which is grouped under a leader will receive a 10 point
increase due to moral improvements, and any army unit whose leader is
in the same sector sector, but not directly leading them will receive
a 5 point increase for the same reasons.
.PP
The efficiency/health of the unit will be weighted against the combat
bonus; for every 2% of efficiency lost (or gained), 1% of the combat
bonus will be removed (or added).  The sections which follow will
provide the exact numbers for each of the various bonus calculations.
.CE
.CS "Terrain Bonuses"
.PP
The actual terrain on which the battle takes place will have an impact
into the amount of bonus a defending unit receives in combat.  So, the
elevation and vegetation of the sector will determine the defensive
bonus for the sector.
.PP
Any such bonuses associated with the elevations and vegetations are:
.TB
            Mountain      +40             Jungle      +30
            Valley        +30             Swamp       +30
            Hill          +20             Forest      +20
                                          Wood        +10
.TE
.PP
There are also magical bonuses for a sector, which will be gained
whether the unit is attacking or defending.  The list of such bonuses
is:
.TB
          Amphibian     +30 for Swamp or Jungle vegetation
          Botany        +5 for Forest vegetation or +2 for Wood
          Dervish       +20 for Desert or Ice vegetation
          Destroyer     +20 for Desert of Ice vegetation
          Earth         -10 for Water sectors, +20 for Mountains
          Marines       +20 for Water sectors
          Sailor        +10 for Water sectors
          Druidism      +20 for Forest vegetation or +10 for Wood
          Water         +5 for Swamp vegetation, +30 for Water sectors
.TE
.CE
.CS "Status Bonuses"
.PP
The status of the unit is the greatest factor for determining the
combat bonus of that unit.  First, it selects whether or not attack or
defense bonuses will be used, and then it determines if terrain and
fortification bonuses are to be used.
.PP
Thus, each status can have an enormous impact on the combat bonus
of the unit.  The summary of status information is as follows:
.TB
    Status       Bonus       Notes about status...
   =========    =======     ==========================================
    Sortie        +50        Attack; +50 bonus not against Sweepers.
    Ambush        +30        Attack; Gain terrain bonus if entrenched
    Attack        +20        Attack; Perform a normal attack
    Engage        +20        Attack; May attack others in 1 sector range
    Defend        +20        Defend, Terrain; 
    Garrison      +30        Defend, Terrain, Fortification;
    Onboard       +30        Defend, Terrain;
    Siege         +20        Defend, Terrain;
    Sieged        -20        Defend, Terrain, Fortification;
    Reserve        +0        Defend, Terrain, Fortification, Protected;
    Sweep          +0        Attack; Avoid Fortifications
    WorkCrew      -40        Defend, Terrain;
    Traded         +0        Defend, Terrain, Fortification, Protected;
    Carry         +10        Defend, Terrain, Fortified, Protected;
    Lure          +20        Defend, Terrain, Fortified, Protected; Visible
    Support        +0        Defend, Terrain, Fortified, Protected; Supplying
    Repair        -30        Defend, Terrain, Fortified, Protected; Repairing
    Onbrd Sppt    +20        Defend, Terrain; Fortified, Protected; Supplying
    Self Sppt      +0        Defend, Terrain; Fortified, Protected; Supplying
    OnbSelfSppt   +20        Defend, Terrain; Fortified, Protected; Supplying
    Rover         +10        Attack; Automated Land Capture
.TE
.PP
If naval units are in a land sector, they are considered to be on
defend, and protected by any fortifications if the sector is owned or
allied, and thus are classified as Protected.  Caravan units are
treated much the same as naval units on land.  They are always on
defend, and they are always treated as Protected.
.CE
.CS "Inflicting the Damage"
.PP
When the damage for each side has been calculated, this damage will
then be inflicted upon all of the units in the sector.  Those units
with a higher combat bonus than the average will receive less damage,
while those with a lower combat bonus will receive more.  This
reflects the likelihood that better troops would be less prone to
damage than less capable ones.
.PP
Once the damage appropriate for each unit has been determined, it will
be inflicted upon the unit.  For normal soldiers, this indicates the
number of percentage of soldiers in the unit which were killed.  With
monsters and leaders, this indicates the percent chance that a monster
or leader will be killed; If it survives that attempt, it will suffer
no damage at all.
.PP
For navies, the damage value indicates the chance for the ships being
destroyed and the crew onboard being killed.  While, for caravans, it
indicates the percent of casualties in crew along with the chance that
the wagons will be destroyed.
.PP
Anyway, the result of all this is that something or someone will get
hurt, it is just a matter of who and how badly.
.CE
.CS "An Example Battle"
.PP
I will give a quick overview of an example battle, so that you can
better understand the results of your own fighting.
.SB
   balkar Attacking force meets lizard Defending force
   Battle Odds = 2.1 to 1
.sp 1
     Attacking balkar Army Merc_Hv_Cav 203; men=1500 (210%) [390 killed]
     Attacking balkar Army Infantry 200; men=200 (120%) [92 killed]
     Attacking balkar Hero 100; str=3x100 (120%) [2 killed]
    balkar: Strength Level = 2000;  Avg Bonus = 187.5%
    balkar: Roll = 41; Avg Damage = 30%; Deaths = 484
.sp 1
     Defending lizard Army Infantry 214; men=870 (200%) [522 killed]
    lizard: Strength Level = 870;  Avg Bonus = 200.0%
    lizard: Roll = 49; Avg Damage = 60%; Deaths = 522
.sp 2
   balkar Attacking force meets lizard Fortified force
   Battle Odds = 1 to 2.3
.sp 1
     Attacking balkar Army Merc_Hv_Cav 203; men=1110 (210%) [765 killed]
     Attacking balkar Army Infantry 200; men=108 (120%) [108 killed]
     Attacking balkar Hero 100; str=1x100 (120%) [1 killed]
    balkar: Strength Level = 1318;  Avg Bonus = 195.8%
    balkar: Roll = 62; Avg Damage = 75%; Deaths = 874
.sp 1
     Fortified lizard Army Archers 215; men=1705 (350%) [664 killed]
    lizard: Strength Level = 1705;  Avg Bonus = 350.0%
    lizard: Roll = 52; Avg Damage = 39%; Deaths = 664
.SE
.PP
In the above example, nation balkar has an Attacking force composed of
1500 Mercenary Heavy Cavalry, 500 Infantry and 3 Heroes attacking a
lizard fortification.  The lizard forces consist of 870 Infantry on
defend and 1705 Archers on garrison.  Notice how the Mercenary troops
have a much higher combat bonus than the rest of the troops in the
nation.  This is mostly due to the fact that balkar has lower combat
bonuses than the Mercenary combat bonuses.
.PP
Even though the balkar Attacking force defeated the lizard Defending
force, balkar got unlucky and lost two Heroes when losing only one was
likely.  It is important to note that in this clash, even though the
Attacking force had almost two and a half times the troops, the odds
were much less due to the lizards having a higher average combat
bonus.
.PP
Finally, the attacking force was virtually destroyed when it ran into
the Fortified force within the lizard stockade.  Not only were the
total number of troops greater, but the average combat bonus was
significantly higher.  In this clash, the difference in damage between
the various components of the balkar force is rather obvious, with the
Infantry being totally decimated, and the Mercs receiving only 69%
damage.  Overall, it looks as though balkar should have avoided this
conflict, given the greater amount of damage which the forces of
balkar took.  It was definitely tactical mistake to have the troops on
attack instead of sweep, since the fortified lizard troops would not
have been encountered otherwise.
.CE
.CS "Recovering from Combat"
.PP
Often you will find your armies, navies or caravans limping around
damaged after a conflict or due to starvation.  When this happens you
will have to take those units aside and heal or repair them.
.PP
Armies may be repaired in two manners: they can be given lighter
Garrison or Reserve duty to slowly heal their wounds, or they can be
magically healed using the spellcasters of the nation.  The best form
of physical rest is when a unit is on Reserve status in a supply
center, which amounts to a reduced garrison status.  The second best
is that of Garrison.  No matter what the unit status, the season of
the year, the sector vegetation and the sector elevation will affect
the amount of healing a unit will receive.
.PP
The magical healing will be a quick and immediate heal for the unit,
but the unit will not be able to receive the normal physical recovery
during the update.  A unit may only be healed once each month due to
the magical strain.
.RF "Powers" "Magical Powers"
.PP
Navies and caravans require that the ships and wagons composing the
units be repaired.  It will take the same amount of materials as
needed in originally building the unit, multiplied with the percent of
damage which the unit has received.  This rebuilding will take a month
worth of work, with the unit being immediately set to Repair status
and the not being able to move on the next update.
.CE
.CS "Laying Siege to a Sector"
.PP
When it is not possible to capture a sector swiftly and decisively
through an aggressive attack, it can be beneficial to cut that sector
off from any support it might receive from its owner and allies.  This
can be done by placing the sector under siege using your armed forces.
.PP
To place a sector under siege, your besieging forces will need to be
double the number of forces which the owner of the sector has within
it.  If this is not possible, then the sector will not be under siege,
and free motion and commerce will still be allowed into and out of the
sector.
.PP
Once a sector is under siege, fortified troops within the sector will
be trapped inside the fortifications, and commerce with other sectors
will be halted.  Any troops outside the sector will be unable to
retreat into the fortifications, and external troops will be hard
pressed to break the siege.  Basically, access to external help will
be greatly diminished, and even Mercenary units will be reluctant to
help out.
.CE
.CS "The command-unit Function"
.PP
The quickest method for setting unit statuses, speeds and supplies is
to use the "command-unit" function.  This function provides access to
a list of options which allows the manipulation of the current army,
navy or caravan unit.  The list of possible options will be displayed
at the bottom of the screen, and all valid options will be
highlighted.  To find out why an option is unavailable, simply select
it.
.PP
These options, which may be thought of as "extended commands", are
usually composed of the lists of possible unit statuses, speed
selections, or unit manipulations.  These extended commands will be
the most used method for assigning tasks to units, so time should be
spent learning all of them.
.PP
The next few documentation sections will describe the various options
available for each of the army, navy and caravan types.
.CE
.CS "The Army Unit Extended Commands"
.PP
The list of extended commands for armies is:
.SB
 (?) Info, (+) Combine, (M)erge, (-) Split, (/) Split 1/2, (U)ngroup, (G)roup,
 (#) Renum, (<) Slow, (=) Norm, (>) Fast, (D)isband, (S)upply, (!) Adj Ldr,
 (A)mbush, (a)ttack, (E)ngage, (d)efend, (g)arrison, (L)ay Siege, (R)eserve,
 S(w)eep, Ro(v)er
.SE
.PP
The first option, Info, will provide additional information about the
current unit.  Things such as the unit strength, movement potential,
efficiency and supply information will be shown in a compact display
at the bottom of the screen.  Unit disbanding is done through the
Disband option, and the Supply option allows adjustments to be made to
the units supply level.  If an individual unit needs to be renumbered,
the Renumber option may be used.  To renumber more than one unit at a
time, the "auto-army-numbering" function is available.
.PP
There are options available to join two units of the same type into a
single unit.  The Combine option will try to merge the current unit
and the unit following the current unit, while the Merge option will
ask for a unit to be joined to the current unit.  Separating units in
two is done using the Split and Split 1/2 options, with the first
querying for number of troops to be separated and the second assuming
that an even division will be made.
.PP
Assigning or deassigning a unit to a group is possible using the Group
or Ungroup options.  Once in a group, units will follow the group
leader and use the orders of the leader as their own.  In combat,
grouped units will gain combat bonuses from the grouping, so being
grouped can have added advantages.  While not grouped, the commander
of a unit may be selected using the Adjust Leader option.  This will
come into play in a combat situation, where a small bonus is given if
the leader of a unit is within the same sector.
.PP
The remaining options show any assignable statuses.  If the option is
highlighted, it is available to the current unit.  Be careful when
launching a Sortie, though, since once started, the unit cannot turn
back from it.
.PP
.CE
.CS "The Navy Unit Extended Commands"
.PP
The list of extended commands for navies is:
.SB
 (?) Info, (+) Combine, (M)erge, (-) Split Navy, (/) Separate Types,
 (#) Renumber, (<) Slow, (=) Norm, (>) Fast, (D)isband, (S)upply,
 (R)epair, (T)fer Cargo, (a)ttack, (E)ngage, (C)arry, (L)ure, Su(p)port,
 Sel(f)Sppt
.SE
.PP
As with the army extended commands, the Info option provides detailed
status information about the current unit.  The Combine and Merge
selections are exactly like those for the army extended commands, as
are the Disband, Supply, Renumber and various speed selector options.
The Split Navy option allows the separation of unit, with selections
made for each ship type and size.  The Separate Types option is
available to quickly break fleets into the various ship types, which
is very convenient for when you need to get the most speed out of your
warships, galleys, or merchants when they might be grouped with a
slower type.
.PP
The other options all pertain to the status of the fleet, and deal
with either support of units using supplies stored on the fleet, or
with the attack and defend status of the unit.  Refer to the list of
unit statuses previously discussed in this section of the
documentation for more information.
.CE
.CS "The Caravan Unit Extended Commands"
.PP
The list of extended commands for caravans is:
.SB
 (?) Info, (+) Combine, (M)erge, (-) Split Caravan, (/) Divide in Two,
 (#) Renumber, (<) Slow, (=) Norm, (>) Fast, (D)isband, (S)upply,
 (R)epair, (T)fer Cargo, (C)arry, (L)ure, Su(p)port, Sel(f)Sppt
.SE
.PP
Once again, the Info, Combine, Merge, Renumber, Disband, Supply and
speed selection options are much like those in the army and navy
extended command sets.  Simply select the option to perform the
desired command.  The Split Caravan and Divide in Two options behave
much like the division options in the army extended command list, but
the caravans may only be separated into sets of 10 wagons, somewhat
limiting the flexibility of unit resizing.
.PP
The remaining status options most closely resemble those available for
the navy extended commands.  Simply select a new status to have the
caravan follow new orders.
.CE
.CS "The Complete List of Army Types:"
.TB
  Army Type   Class   Values  Atk Dfd Move  Traits    Enlist   Supply  Rqrmnts
 =========== ======= ======== === === ==== ======== ========== ====== =========
 King        Leader       100 +30 +30 2.0x FR       --         --     --
 Baron       Leader        50 +20 +20 2.0x F        --         --     --
 Emperor     Leader       100 +30 +30 2.0x FR       --         --     --
 Prince      Leader        50 +20 +20 2.0x F        --         --     --
 Wizard      Leader       250 +30 +30 2.0x FFcRSc   --         --     --
 Mage        Leader        50 +20 +20 2.0x FSc      --         --     --
 Pope        Leader       100 +30 +30 2.0x RF       --         --     --
 Cardinal    Leader        50 +20 +20 2.0x F        --         --     --
 Admiral     Leader       100 +30 +30 2.0x FR       --         --     --
 Captain     Leader        50 +20 +20 2.0x F        --         --     --
 Warlord     Leader       250 +35 +35 2.0x FR       --         --     --
 Lord        Leader       125 +30 +30 2.0x F        --         --     --
 Demon       Leader       250 +50 +50 2.0x FR       --         --     --
 Devil       Leader        75 +20 +20 2.0x F        --         --     --
 Dragyn      Leader       500 +50 +50 2.0x FR       --         --     --
 Wyrm        Leader       100 +40 +40 2.0x F        --         --     --
 Shadow      Leader       250 +50 +50 2.0x FRU      --         --     --
 Nazgul      Leader       125 +40 +40 2.0x FU       --         --     --
 Sorcerer    Caster       100 +10 +10 1.0x FFcSc    --         --     --
 Magician    Caster        50  +0  +0 1.0x Sc       --         --     --
 Spirit      Monster    50/15  +0  +0 1.0x Fl       1800J,1p   1000J  
 Assassin    Monster    50/25 +20 +20 1.0x SiSl     1400J,2p   1000J  Ninja
 Efreet      Monster    50/20 +10 +10 1.5x Fl       1200J,2p   800J   Air
 Gargoyle    Monster    75/17 +10 +10 1.0x Fl       2000J,2p   1150J  Orc
 Wraith      Monster    75/25 +10 +10 1.0x U        2000J,3p   1300J  VampVoid
 Hero        Monster   100/30  +0  +0 1.0x          1600J,3p   800J   Warrior
 Centaur     Monster    75/25 +10 +10 1.5x          1700J,3p   800J   Equine
 Lich        Monster   100/30  +0  +0 1.0x FcNoScU  --         1200J  Vampire
 Giant       Monster   150/50  +0  +0 1.0x D        2500J,5p   2100J  
 SuperHero   Monster   150/50 +15 +15 1.0x          2600J,5p   1200J  Captain+
 Mummy       Monster   150/40 +15 +15 1.0x U        2300J,5p   1600J  Vampire
 Earthmental Monster   175/60  +5  +5 1.5x DE       2500J,6p   2000J  Earth
 Minotaur    Monster   150/50 +20 +20 1.0x          2500J,8p   1800J  Wyzard
 Daemon      Monster  500/130 +50 +50 1.0x          10000J,10p 6000J  OrcSorc+
 Balrog      Monster  500/150 +40 +40 1.5x FlFi     12000J,12p 6000J  OgrFirSrc
 Dragon      Monster 1000/300 +50 +50 2.0x DFlFiSc  20000J,15p 10000J DrgSrc+
 Militia     Normal       0.5 -40 -25 0.0x H        50T        20T
 Goblins     Orcish       0.8 -15 -15 1.0x          70T,80M    20T    Orc
 Orcs        Orcish       1.0  +0  +0 1.0x          85T,80M    50T    Orc
 Infantry    Normal       1.0  +0  +0 1.0x          100T,100M  50T
 Sailors     Sailors      1.0  +0  +0 0.0x B        100T,100M  50T
 Marines     Sailors      1.1  +5  +0 0.0x AB       100T,100M  50T    Sailor
 Assault     Sailors      1.2 +10  +5 0.5x AB       125T,120M  60T    Marine+
 Archers     Archers      1.1  +0 +10 1.0x AaBa     100T,100M  50T    Archery
 Uruk-Hai    Orcish       1.0  +5  +5 1.0x          125T,150M  50T    Ogre+
 Ninjas      Normal       1.0 +20  +0 1.0x SiSlT    125T,150M  50T    Ninja
 Longbowmen  Archers      1.1  +5 +15 1.0x AaBa     150T,150M  65T    ArchWarr
 Phalanx     Normal   500|1.1 +10 +10 1.0x N        150T,150M  60T    Captain+
 Bow_Phalanx Archers  500|1.1 +20 +20 1.0x AaBaN    170T,160M  80T    ArchCapt+
 Olog-Hai    Orcish       1.1 +15 +15 1.0x          180T,150M  75T    DrgBreed+
 Legionaries Normal  1000|1.1 +20 +20 1.0x N        180T,150M  80T    Warlord+
 Dragoons    Cavalry      1.1 +10 +10 1.5x          200T,100M  150T   ArchWrld+
 Full_Bowmen Archers 1000|1.2 +30 +30 1.0x AaBaN    200T,160M  110T   ArchWrld+
 Crossbows   Archers      1.2 +40  +0 1.0x AaBa     200T,200M  130T
 Mercenaries Merc         1.0  +0  +0 1.0x DaP      225T       100T
 Merc_Arch   Merc         1.0  +0 +10 1.0x AaBaDaP  250T       110T
 Merc_Asslt  Merc         1.0 +10  +5 0.5x ABDaP    275T       120T
 Merc_Drag   Merc         1.1 +10 +10 1.5x DaP      300T       160T
 Merc_Lt_Cav Merc         1.1 +20 +20 2.0x DaP      350T       200T
 Merc_Hv_Cav Merc         1.2 +30 +30 1.8x DaP      500T       275T
 Merc_Rocs   Merc         1.2 +20 +30 1.0x AwDaFlP  750T       400T
 Trolls      Unique       1.3 +25 +15 1.0x          225T,200M  100T   DrgnWyzd+
 Elite       Normal       1.3 +20 +20 1.3x          225T,200M  100T   Armor
 Hvy_Bowmen  Archers 2000|1.3 +40 +30 1.0x AaBaN    240T,225M  120T   ArcArmWd+
 Lt_Cavalry  Cavalry      1.3 +20 +20 2.0x          300T,100M  175T   EqneWarr
 Hv_Cavalry  Cavalry      1.4 +30 +30 1.8x          450T,300M  225T   EqneCapt+
 Catapults   Unique  (500)1.6 -20 -20 0.5x BaCD     600T,800M  250T
 Siege_Engs  Unique  (400)1.8 -20 -20 0.5x CD       600T,800M  250T
 Rocs        Unique       1.3 +20 +30 1.0x AwFl     600T,300M  250T   AvianWarr
 Knights     Cavalry      1.5 +40 +40 2.0x Aw       600T,600M  250T   EqArmCpt+
 Griffons    Unique       1.5 +40 +50 1.5x AwFl     800T,400M  250T   AvnWlord+
 Elephants   Unique       2.0 +50 +50 0.5x D        600T,600M  250T   Dervish
 Ghosts      Unique       0.2 -55 -55 0.5x DaFNoU   --         --     Vampire
 Skeletons   Unique       0.6 -35 -35 0.5x DaDyFNoU --         --     Vampire
 Zombies     Unique       0.8 -25 -25 0.5x DaDyFU   100T,100M  --     Vampire
 Scout       Scout          0 -30 -30 1.0x DaFSl    100T,100M  --
 Spy         Scout          0 -30 -30 1.0x DaSiSlT  10000T     2000T
 Cvlry Scout Scout          0 -15 -15 2.0x DaFSl    1000T,150M --     Equine
 Wingd Scout Scout          0  +0  +0 2.0x DaFFlSl  1500T,200M --     Avian
 Mounted Spy Scout          0 -20 -20 2.0x DaSiSlT  15000T     3000T  Equine
 Winged Spy  Scout          0 -10 -10 2.0x DaFlSiSlT 20000T    4000T  Avian
 Informant   Agent          0 -30 -30 0.5x DaPReSl  6000T      2000T
 Agent       Agent          0 -30 -30 0.5x DaPReSiSlT 60000T   30000T
 Surveyor    Scout         75 -30 -30 0.4x MSiSlT   10000T     5000T
.sp
      Unless noted below, the Value represents how much a single soldier
         of the given unit is worth when capturing a sector.
.sp
      Leader and Caster class units have starting experience values shown
         and are only worth 1 man each when capturing a sector.
.sp
      A/B ::: Combat value A and capture value B of monster units.
.sp
      A|B ::: For Needmin units, A indicates men required before a
         the appropriate combat bonus is given to the unit.
.sp
      (A)B ::: A indicates the men needed to obtain a +20 combat bonus
         to any allied troops within the combat.
.sp
      The list of traits is:  Assault=A, Anti-Air=Aa, Arrowweak=Aw,
         Beachhead=B, Ballistics=Ba, Coverbonus=C, Damaging=D,
         Disband-Anywhere=Da, Decay=Dy, Earth=E, Free-Supplies=F,
         Fullcaster=Fc, Fire=Fi, Flight=Fl, Half-Recruits=H,
         Mapping=M, Needmin=N, Nodraft=No, Payoff=P, Ruler=R,
         Remote-Enlist=Re, Sapper=Sa, Spellcaster=Sc, Sight=Si, 
         Slippery=Sl, Ruler=R, Training=T, Undead=U.
.TE
.CE
