"""add world admins

Revision ID: 180b7cdd29c3
Revises: 4c63244c0aef
Create Date: 2026-02-26 17:50:11.576554

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180b7cdd29c3'
down_revision: Union[str, None] = '4c63244c0aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_admins',
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'user_id')
    )
    op.add_column('worlds', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'worlds', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worlds', type_='foreignkey')
    op.drop_column('worlds', 'creator_id')
    op.drop_table('world_admins')
    # ### end Alembic commands ###
