"""initial schema

Revision ID: 4c63244c0aef
Revises: 
Create Date: 2026-02-26 16:57:27.114231

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c63244c0aef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('worlds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mapx', sa.SmallInteger(), nullable=False),
    sa.Column('mapy', sa.SmallInteger(), nullable=False),
    sa.Column('turn', sa.SmallInteger(), nullable=False),
    sa.Column('start_turn', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_maintenance', sa.Boolean(), nullable=False),
    sa.Column('demigod_name', sa.String(length=10), nullable=False),
    sa.Column('world_population', sa.BigInteger(), nullable=False),
    sa.Column('world_military', sa.BigInteger(), nullable=False),
    sa.Column('world_sectors', sa.Integer(), nullable=False),
    sa.Column('world_score', sa.BigInteger(), nullable=False),
    sa.Column('w_talons', sa.BigInteger(), nullable=False),
    sa.Column('w_jewels', sa.BigInteger(), nullable=False),
    sa.Column('w_metals', sa.BigInteger(), nullable=False),
    sa.Column('w_food', sa.BigInteger(), nullable=False),
    sa.Column('w_wood', sa.BigInteger(), nullable=False),
    sa.Column('lizard_count', sa.SmallInteger(), nullable=False),
    sa.Column('savage_count', sa.SmallInteger(), nullable=False),
    sa.Column('nomad_count', sa.SmallInteger(), nullable=False),
    sa.Column('pirate_count', sa.SmallInteger(), nullable=False),
    sa.Column('merc_military', sa.BigInteger(), nullable=False),
    sa.Column('merc_attack_bonus', sa.SmallInteger(), nullable=False),
    sa.Column('merc_defense_bonus', sa.SmallInteger(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('leader_title', sa.String(length=10), nullable=False),
    sa.Column('race', sa.String(length=20), nullable=False),
    sa.Column('player_class', sa.String(length=30), nullable=False),
    sa.Column('mark', sa.String(length=1), nullable=False),
    sa.Column('capital_x', sa.SmallInteger(), nullable=False),
    sa.Column('capital_y', sa.SmallInteger(), nullable=False),
    sa.Column('center_x', sa.SmallInteger(), nullable=False),
    sa.Column('center_y', sa.SmallInteger(), nullable=False),
    sa.Column('attack_bonus', sa.SmallInteger(), nullable=False),
    sa.Column('defense_bonus', sa.SmallInteger(), nullable=False),
    sa.Column('max_movement', sa.SmallInteger(), nullable=False),
    sa.Column('reproduction_rate', sa.SmallInteger(), nullable=False),
    sa.Column('is_npc', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('score', sa.BigInteger(), nullable=False),
    sa.Column('victory_points', sa.BigInteger(), nullable=False),
    sa.Column('total_civilians', sa.BigInteger(), nullable=False),
    sa.Column('total_military', sa.BigInteger(), nullable=False),
    sa.Column('total_monsters', sa.BigInteger(), nullable=False),
    sa.Column('total_leaders', sa.BigInteger(), nullable=False),
    sa.Column('total_sectors', sa.Integer(), nullable=False),
    sa.Column('total_ships', sa.SmallInteger(), nullable=False),
    sa.Column('total_wagons', sa.SmallInteger(), nullable=False),
    sa.Column('talons', sa.BigInteger(), nullable=False),
    sa.Column('jewels', sa.BigInteger(), nullable=False),
    sa.Column('metals', sa.BigInteger(), nullable=False),
    sa.Column('food', sa.BigInteger(), nullable=False),
    sa.Column('wood', sa.BigInteger(), nullable=False),
    sa.Column('talons_produced', sa.BigInteger(), nullable=False),
    sa.Column('jewels_produced', sa.BigInteger(), nullable=False),
    sa.Column('metals_produced', sa.BigInteger(), nullable=False),
    sa.Column('food_produced', sa.BigInteger(), nullable=False),
    sa.Column('wood_produced', sa.BigInteger(), nullable=False),
    sa.Column('power_fire', sa.BigInteger(), nullable=False),
    sa.Column('power_water', sa.BigInteger(), nullable=False),
    sa.Column('power_earth', sa.BigInteger(), nullable=False),
    sa.Column('attr_charity', sa.SmallInteger(), nullable=False),
    sa.Column('attr_comm_range', sa.SmallInteger(), nullable=False),
    sa.Column('attr_currency', sa.SmallInteger(), nullable=False),
    sa.Column('attr_eat_rate', sa.SmallInteger(), nullable=False),
    sa.Column('attr_health', sa.SmallInteger(), nullable=False),
    sa.Column('attr_inflation', sa.SmallInteger(), nullable=False),
    sa.Column('attr_jewelwork', sa.SmallInteger(), nullable=False),
    sa.Column('attr_knowledge', sa.SmallInteger(), nullable=False),
    sa.Column('attr_merc_rep', sa.SmallInteger(), nullable=False),
    sa.Column('attr_metalwork', sa.SmallInteger(), nullable=False),
    sa.Column('attr_mining', sa.SmallInteger(), nullable=False),
    sa.Column('attr_morale', sa.SmallInteger(), nullable=False),
    sa.Column('attr_popularity', sa.SmallInteger(), nullable=False),
    sa.Column('attr_reputation', sa.SmallInteger(), nullable=False),
    sa.Column('attr_spell_pts', sa.SmallInteger(), nullable=False),
    sa.Column('attr_spoil_rate', sa.SmallInteger(), nullable=False),
    sa.Column('attr_tax_rate', sa.SmallInteger(), nullable=False),
    sa.Column('attr_terror', sa.SmallInteger(), nullable=False),
    sa.Column('attr_wiz_skill', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nations_user_id'), 'nations', ['user_id'], unique=False)
    op.create_index(op.f('ix_nations_world_id'), 'nations', ['world_id'], unique=False)
    op.create_table('armies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nation_id', sa.UUID(), nullable=False),
    sa.Column('unit_type', sa.SmallInteger(), nullable=False),
    sa.Column('max_efficiency', sa.SmallInteger(), nullable=False),
    sa.Column('efficiency', sa.SmallInteger(), nullable=False),
    sa.Column('x', sa.SmallInteger(), nullable=False),
    sa.Column('y', sa.SmallInteger(), nullable=False),
    sa.Column('target_x', sa.SmallInteger(), nullable=True),
    sa.Column('target_y', sa.SmallInteger(), nullable=True),
    sa.Column('last_x', sa.SmallInteger(), nullable=True),
    sa.Column('last_y', sa.SmallInteger(), nullable=True),
    sa.Column('strength', sa.BigInteger(), nullable=False),
    sa.Column('movement', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('spell_points', sa.SmallInteger(), nullable=False),
    sa.Column('supply', sa.SmallInteger(), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['armies.id'], ),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_armies_nation_id'), 'armies', ['nation_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('effect_type', sa.String(length=50), nullable=False),
    sa.Column('effect_value', sa.Float(), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('holder_nation_id', sa.UUID(), nullable=True),
    sa.Column('sector_x', sa.SmallInteger(), nullable=True),
    sa.Column('sector_y', sa.SmallInteger(), nullable=True),
    sa.Column('is_guarded', sa.Boolean(), nullable=False),
    sa.Column('is_revealed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['holder_nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_holder_nation_id'), 'artifacts', ['holder_nation_id'], unique=False)
    op.create_index(op.f('ix_artifacts_world_id'), 'artifacts', ['world_id'], unique=False)
    op.create_table('caravans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nation_id', sa.UUID(), nullable=False),
    sa.Column('efficiency', sa.SmallInteger(), nullable=False),
    sa.Column('x', sa.SmallInteger(), nullable=False),
    sa.Column('y', sa.SmallInteger(), nullable=False),
    sa.Column('target_x', sa.SmallInteger(), nullable=True),
    sa.Column('target_y', sa.SmallInteger(), nullable=True),
    sa.Column('last_x', sa.SmallInteger(), nullable=True),
    sa.Column('last_y', sa.SmallInteger(), nullable=True),
    sa.Column('size', sa.SmallInteger(), nullable=False),
    sa.Column('movement', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('crew', sa.SmallInteger(), nullable=False),
    sa.Column('people_per_wagon', sa.SmallInteger(), nullable=False),
    sa.Column('supply', sa.SmallInteger(), nullable=False),
    sa.Column('cargo_talons', sa.BigInteger(), nullable=False),
    sa.Column('cargo_jewels', sa.BigInteger(), nullable=False),
    sa.Column('cargo_metals', sa.BigInteger(), nullable=False),
    sa.Column('cargo_food', sa.BigInteger(), nullable=False),
    sa.Column('cargo_wood', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caravans_nation_id'), 'caravans', ['nation_id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('nation_id', sa.UUID(), nullable=True),
    sa.Column('x', sa.SmallInteger(), nullable=False),
    sa.Column('y', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('initial_population', sa.SmallInteger(), nullable=False),
    sa.Column('efficiency', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.Column('fortress', sa.SmallInteger(), nullable=False),
    sa.Column('talons', sa.BigInteger(), nullable=False),
    sa.Column('jewels', sa.BigInteger(), nullable=False),
    sa.Column('metals', sa.BigInteger(), nullable=False),
    sa.Column('food', sa.BigInteger(), nullable=False),
    sa.Column('wood', sa.BigInteger(), nullable=False),
    sa.Column('init_talons', sa.BigInteger(), nullable=False),
    sa.Column('init_jewels', sa.BigInteger(), nullable=False),
    sa.Column('init_metals', sa.BigInteger(), nullable=False),
    sa.Column('init_food', sa.BigInteger(), nullable=False),
    sa.Column('init_wood', sa.BigInteger(), nullable=False),
    sa.Column('start_talons', sa.BigInteger(), nullable=False),
    sa.Column('min_talons', sa.BigInteger(), nullable=False),
    sa.Column('min_jewels', sa.BigInteger(), nullable=False),
    sa.Column('min_metals', sa.BigInteger(), nullable=False),
    sa.Column('min_food', sa.BigInteger(), nullable=False),
    sa.Column('min_wood', sa.BigInteger(), nullable=False),
    sa.Column('auto_flags', sa.JSON(), nullable=False),
    sa.Column('cmd_flag', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_nation_id'), 'cities', ['nation_id'], unique=False)
    op.create_index(op.f('ix_cities_world_id'), 'cities', ['world_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nation_id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('cmd_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('x', sa.SmallInteger(), nullable=True),
    sa.Column('y', sa.SmallInteger(), nullable=True),
    sa.Column('param_int', sa.Integer(), nullable=True),
    sa.Column('param_str', sa.String(length=255), nullable=True),
    sa.Column('result_msg', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_nation_id'), 'commands', ['nation_id'], unique=False)
    op.create_index(op.f('ix_commands_world_id'), 'commands', ['world_id'], unique=False)
    op.create_table('diplomatic_relations',
    sa.Column('nation_id', sa.UUID(), nullable=False),
    sa.Column('target_nation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['target_nation_id'], ['nations.id'], ),
    sa.PrimaryKeyConstraint('nation_id', 'target_nation_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('sender_nation_id', sa.UUID(), nullable=True),
    sa.Column('recipient_nation_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('turn_sent', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['sender_nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_recipient_nation_id'), 'messages', ['recipient_nation_id'], unique=False)
    op.create_index(op.f('ix_messages_world_id'), 'messages', ['world_id'], unique=False)
    op.create_table('sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('owner_nation_id', sa.UUID(), nullable=True),
    sa.Column('x', sa.SmallInteger(), nullable=False),
    sa.Column('y', sa.SmallInteger(), nullable=False),
    sa.Column('designation', sa.SmallInteger(), nullable=False),
    sa.Column('altitude', sa.SmallInteger(), nullable=False),
    sa.Column('vegetation', sa.SmallInteger(), nullable=False),
    sa.Column('efficiency', sa.SmallInteger(), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('minerals', sa.SmallInteger(), nullable=False),
    sa.Column('tradegood', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'x', 'y', name='uq_sector_world_xy')
    )
    op.create_index(op.f('ix_sectors_owner_nation_id'), 'sectors', ['owner_nation_id'], unique=False)
    op.create_index(op.f('ix_sectors_world_id'), 'sectors', ['world_id'], unique=False)
    op.create_table('world_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('target_nation_id', sa.UUID(), nullable=True),
    sa.Column('chain_parent_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('affected_sectors', sa.JSON(), nullable=False),
    sa.Column('turns_remaining', sa.SmallInteger(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('display_icon', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_parent_id'], ['world_events.id'], ),
    sa.ForeignKeyConstraint(['target_nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_events_world_id'), 'world_events', ['world_id'], unique=False)
    op.create_table('navies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nation_id', sa.UUID(), nullable=False),
    sa.Column('warships', sa.SmallInteger(), nullable=False),
    sa.Column('merchants', sa.SmallInteger(), nullable=False),
    sa.Column('galleys', sa.SmallInteger(), nullable=False),
    sa.Column('barges', sa.SmallInteger(), nullable=False),
    sa.Column('warship_eff', sa.SmallInteger(), nullable=False),
    sa.Column('merchant_eff', sa.SmallInteger(), nullable=False),
    sa.Column('galley_eff', sa.SmallInteger(), nullable=False),
    sa.Column('barge_eff', sa.SmallInteger(), nullable=False),
    sa.Column('x', sa.SmallInteger(), nullable=False),
    sa.Column('y', sa.SmallInteger(), nullable=False),
    sa.Column('target_x', sa.SmallInteger(), nullable=True),
    sa.Column('target_y', sa.SmallInteger(), nullable=True),
    sa.Column('last_x', sa.SmallInteger(), nullable=True),
    sa.Column('last_y', sa.SmallInteger(), nullable=True),
    sa.Column('movement', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('crew', sa.SmallInteger(), nullable=False),
    sa.Column('people_per_hold', sa.SmallInteger(), nullable=False),
    sa.Column('supply', sa.SmallInteger(), nullable=False),
    sa.Column('carried_army_id', sa.UUID(), nullable=True),
    sa.Column('carried_caravan_id', sa.UUID(), nullable=True),
    sa.Column('cargo_talons', sa.BigInteger(), nullable=False),
    sa.Column('cargo_jewels', sa.BigInteger(), nullable=False),
    sa.Column('cargo_metals', sa.BigInteger(), nullable=False),
    sa.Column('cargo_food', sa.BigInteger(), nullable=False),
    sa.Column('cargo_wood', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['carried_army_id'], ['armies.id'], ),
    sa.ForeignKeyConstraint(['carried_caravan_id'], ['caravans.id'], ),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navies_nation_id'), 'navies', ['nation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_navies_nation_id'), table_name='navies')
    op.drop_table('navies')
    op.drop_index(op.f('ix_world_events_world_id'), table_name='world_events')
    op.drop_table('world_events')
    op.drop_index(op.f('ix_sectors_world_id'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_owner_nation_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_messages_world_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_nation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('diplomatic_relations')
    op.drop_index(op.f('ix_commands_world_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_nation_id'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_cities_world_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_nation_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_caravans_nation_id'), table_name='caravans')
    op.drop_table('caravans')
    op.drop_index(op.f('ix_artifacts_world_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_holder_nation_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_armies_nation_id'), table_name='armies')
    op.drop_table('armies')
    op.drop_index(op.f('ix_nations_world_id'), table_name='nations')
    op.drop_index(op.f('ix_nations_user_id'), table_name='nations')
    op.drop_table('nations')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
